core/src/main/java/org/eobjects/datacleaner/extension/output/CreateCsvFileAnalyzer.java

Updated code to modify the "columns" variable to include the "column to be sorted on" in case we do not include it in the input columns.
This was done as the "columns" variable was being used to write the rows to the temp file, and thus if a column to be sorted on was selected, then its value would be null in the row written to the temp file (thereby leading to a potential incorrect sorted order in the final file).

Modify the "columns" variable to include the "column to be sorted on" in case we do not include it in the input columns

---

desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraph.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
desktop/ui/src/main/java/org/datacleaner/windows/ComponentConfigurationDialog.java
desktop/ui/src/main/java/org/datacleaner/windows/SourceTableConfigurationDialog.java
engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalyzerChangeListener.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalyzerComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/ComponentChangeListener.java
engine/core/src/main/java/org/datacleaner/job/builder/ComponentRemovalListener.java
engine/core/src/main/java/org/datacleaner/job/builder/FilterChangeListener.java
engine/core/src/main/java/org/datacleaner/job/builder/FilterComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java

This will close dialogs along with nodes and jobs, and adds a way to close all dialogs in the window menu.
It also extends the previous "pull existing component configuration dialog to front" functionality to table configuration dialogs.

Keeping amount of dialogs reasonable.

---

desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraph.java

The code used getPanel(), which refreshed and redrew the entrie panel.
As the result was only used for sizing, there should be no need.
Fixes #186

Do not refresh  panel when checking size.

---

desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLinkPainter.java

JobGraphMouseListener) both act on a right-click and causing an
exception because graph was refreshed inbetween actions.

Fixes an issue where two mouse listeners (JobGraphLinkPainter and

---

monitor/ui/src/main/webapp/WEB-INF/web.xml

The WebappLifecycleListener has no Methods which can be accessed by any Java Application Server. Listener Classes without any declared Listener Interfaces cannot be declared in a web.xml. While Tomcat ignores this, Wildfly and JBoss AS both won't deploy the war. Because the WebappLifecycleListener does not implement any compatible Listener Interface, removing it should not have any impact.

Removed unnecessary WebappLifecycleListener to fix deployment on JBoss/Wildfly

---

desktop/ui/src/main/java/org/datacleaner/windows/OpenAnalysisJobAsTemplateDialog.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java
engine/xml-config/src/test/resources/example-job-only-columns-names-paths.analysis.xml

Fixes #264.  In connection with https://github.com/datacleaner/AnalyzerBeans/issues/58
The dialog for opening as template was prepared to handle column paths that contain the name of the table. However if there is one table as datastore the column path will contain only the column names, which will throw an exception if it doesn't find the table name separated by "." when trying to open the job as a template.

Fixes #264

---

desktop/ui/src/main/java/org/datacleaner/widgets/Dropzone.java

Fixes #240  Check if the datastore catalog already contains the file. If so select the existing datastore. Otherwise create a new one

Dropzone - use existing datastore

---

engine/core/src/main/java/org/datacleaner/job/concurrent/MultiThreadedTaskRunner.java

When the main thread cannot submit task to threadpool (because of the full task queue),  it processes a row itself (CallerRunsPolicy). But if the processing takes a long time, and the other processing threads become ready for new row, they are uselessly waiting for the main thread to feed them. Fixed by "blocking" policy.

When processing rows multi-threaded, sometimes threads can be not utilized.

---

desktop/ui/src/main/java/org/datacleaner/panels/DatastorePanel.java

This moves the checkbox out of the label's flow panel, avoiding the label flowing under the checkbox.
Fixes #263

Do not put datastorepanel checkbox inside flowpanel

---

desktop/ui/src/main/java/org/datacleaner/windows/ResultWindow.java

This should fix the ResultWindows, at least simple ones. We've decided to leave component dialogs alone for now, as the pop-under is much less annoying, especially after the change that does not open new dialogs on an extra click. Also, it doesn't seem to affect all component dialogs (i.e. I couldn't trigger the String Analyzer at all), so we might want to do them on a case-by-case basis.
Fixes #325

Fix pop-under issue

---

monitor/ui/src/main/webapp/login.xhtml

This will make the monitor actually show the error message instead of the raw text.

Use getClass() instead of class as is not allowed in EL

---

desktop/ui/src/main/resources/org/datacleaner/log4j-default.xml
desktop/ui/src/main/resources/org/datacleaner/log4j-jnlp.xml

instead of ./log
Fixes #351 
Changed it to ${user.home}/.datacleaner/log/datacleaner.log however it would be perfect to have ${user.home}/.datacleaner/DATACLEANER.VERSION/log/datacleaner.log, but the version of DC is not available from System properties. 
JNLP already logged to user directory, but for consistency I changed it to .datacleaner subdirectory.

Changed default logging directory to ${user.home}/.datacleaner/log

---

engine/core/src/main/java/org/datacleaner/job/concurrent/JobCompletionTaskListener.java
engine/core/src/main/java/org/datacleaner/job/concurrent/StatusAwareTaskListener.java
engine/core/src/test/java/org/datacleaner/test/full/scenarios/AnalyzerResultFutureAndAnalysisListenerTest.java

Fixes #393 .... The level of readability in the test is decreased I am affraid. But it will no longer fail because of race conditions among certain events in the listeners.

Fixes #393 by only asserting on certain indexes in the events instead of absolute ordering.

---

desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphNodeBuilder.java

Ensures that jobgraph rendering never has redundant lines

---

desktop/api/src/main/java/org/datacleaner/util/IconUtils.java
desktop/api/src/main/java/org/datacleaner/util/LookAndFeelManager.java
desktop/api/src/main/java/org/datacleaner/util/WidgetFactory.java
desktop/api/src/main/java/org/datacleaner/util/WidgetUtils.java
desktop/ui/src/main/java/org/datacleaner/panels/DatabaseDriversPanel.java
desktop/ui/src/main/java/org/datacleaner/widgets/database/OracleDatabaseConnectionPresenter.java

Fixes #406 
(The trick was to add a UIManager property and to make sure our colors are ColorUIResources which are apparently needed in the TextFieldUI classes).
Here's an example dialog with a disabled text field:

Issue #406: Fixed (and also a few icon references)

---

engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobWriter.java
engine/xml-config/src/main/resources/job.xsd

This is the Job XML Schema part of the greater story #224. To make review easier and incremental this bit is pushed. It's actual origin is in PR #417 (which I do not want to have merged yet) from which also #419 was separated out as a "child PR".
This particular part is only about the change pertaining to the XSD (and the generated java classes from this). It is NOT about adapting the job reader+writer to actually support reading+writing output data stream jobs. That part is pending still.

Issue #224: Updated the job.xsd file

---

desktop/ui/src/main/java/org/datacleaner/actions/AbstractJobBuilderPopupListener.java
desktop/ui/src/main/java/org/datacleaner/actions/RemoveComponentMenuItem.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphActions.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphContext.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphKeyListener.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
desktop/ui/src/main/java/org/datacleaner/windows/ComponentConfigurationDialog.java

This is part of the greater story #224. To make review easier and incremental this bit is pushed. It's actual origin is in PR #417 (which I do not want to have merged yet) from which also #419 was separated out as a "child PR".
This particular part is only about preparing the UI handlers to have multiple builder objects in graph which will be the case when #224 is done.

Prepared the UI handlers to have multiple builder objects in graph

---

engine/core/src/main/java/org/datacleaner/util/SecurityUtils.java
engine/core/src/test/java/org/datacleaner/util/SecurityUtilsTest.java
engine/xml-config/src/main/java/org/datacleaner/configuration/DatastoreXmlExternalizer.java
engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
engine/xml-config/src/test/java/org/datacleaner/configuration/DatastoreXmlExternalizerTest.java

This will ensure that in most situations we can externalize datastores of these types to the conf.xml file, instead of saving them in userpreferences.dat.
While this is actually an independent improvement, I imagine that making XML externalization better will in turn make #402 much easier to fix because we can then focus on conf.xml and not on user preferences (more volatile and difficult to migrate)
Fixes #440

Added XML externalization for ElasticSearch, MongoDb, CouchDb and SFDC

---

engine/core/src/main/java/org/datacleaner/output/excel/ExcelOutputWriterFactory.java

This tries to check if column names has been configured properly. If not, it just copies the names from the input columns.
Fixes #444

If no manual columnnames are set, use defaults.

---

engine/core/src/main/java/org/datacleaner/job/concurrent/JobCompletionTaskListener.java

This avoids error in external code from affecting the countdown latches.
Fixes #492

Put latch countdowns in finally block.

---

pom.xml

Downgrading Guava to 16.0.1 in order to ensure compatibility with Hadoop and HBase (which isn't Guava 18 compatible due to Stopwatch class changes).

Downgraded Guava to align with Hadoop dependencies

---

.gitignore
engine/core/src/main/java/org/datacleaner/job/runner/CompositeAnalysisListener.java
engine/core/src/test/java/org/datacleaner/job/runner/CompositeAnalysisListenerTest.java

Wraps every call to a delegate in a try...catch block to assure that following listeners will also be called.
Fixes #504

Protect delegates of CompositeAnalysisListener from each others exceptions

---

desktop/ui/src/main/java/org/datacleaner/windows/AbstractDatastoreDialog.java
desktop/ui/src/main/java/org/datacleaner/windows/CsvDatastoreDialog.java

Instead of a doing full validation on datastore name change, only validate the name itself and enable the save button.
Also added a bit of code cleanup
Fixes #518

Only do a partial validation when updating datastore name.

---

components/basic-filters/src/main/java/org/datacleaner/beans/filter/CaptureChangedRecordsFilter.java
components/basic-filters/src/test/java/org/datacleaner/beans/filter/CaptureChangedRecordsFilterTest.java

Refactored the CaptureChangedRecordsFilter to name the state field as XXX.GreatestLastModifiedValue instead of XXX.GreatestLastModifiedTimestamp. The filter also works with ID fields which contain numbers.

Fix for bug#538

---

engine/core/src/main/java/org/datacleaner/database/DatabaseDriverCatalog.java
engine/core/src/main/java/org/datacleaner/database/DriverPreparer.java
engine/core/src/main/java/org/datacleaner/database/HiveDriverPreparer.java

This forces Derby to use a dummy OutputStream instead of dumping logs to a file.
Fixes #528

Avoid creating a derby.log file

---

desktop/ui/src/main/java/org/datacleaner/widgets/database/HiveDatabaseConnectionPresenter.java
engine/core/src/main/java/org/datacleaner/database/DatabaseDriverCatalog.java

Hive support currently does not work, as the connection string prefix is not accepted by the driver, which expects "jdbc:hive2:". We provide "jdbc:hive:" as the prefix.

Connection prefix jdbc:hive: seems wrong. Driver expects jdbc:hive2:

---

monitor/api/pom.xml
monitor/pom.xml
monitor/services/pom.xml
pom.xml

Replaced proprietary "javax.annotation" package from geronimo with official one.
This doesn't matter much, but it's better to use the standard artifact for the javax stuff.

Replaced proprietary "javax.annotation" package from geronimo

---

engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobWriterTest.java
pom.xml

MetaModel 4.3.6 is most likely to be released today or tomorrow. This PR upgrades our dependency on it and fixes a few other dependency snags that it revealed:
* Unmanaged Jackson version which can create NoClassDefFoundError because of poor artifact resolution.
* Better exclusion of slf4j-log4j and log4j from hadoop-client.

Feature/metamodel 4.3.6

---

components/basic-analyzers/src/main/java/org/datacleaner/beans/CompletenessAnalyzer.java
engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingPublisher.java
engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingPublishers.java
engine/core/src/main/java/org/datacleaner/job/tasks/InitializeTask.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java

This should avoid races between initializers and row processing.
This also extends testing of the reader to ensure that a built job is also runnable. This tests more than the reader, so it might not be the optimal place, but I'm not really sure where it would be, as it is more of an "internal" integration test, testing that the parts assembling and running a job work properly together.
I'll also be lazy and put a small fix of CompletenessAnalyzer on here: There was absolutely no need to create a dataset header, and it actually introduced a bug.
Fixes #563

Initialize consumers in output datastream as part of parent consumer

---

spark/src/main/java/org/datacleaner/spark/SparkJobLauncher.java
spark/src/main/java/org/datacleaner/spark/TransformationAction.java

once per worker and operate on the iterator of rows instead of a single
row at a time.
@kaspersorensen RDD.mapPartitions() is essentially the same as RDD.glom().flatMap(), but it is a preferrable way in some cases.

Using mapPartitions() instead of flatMap() to create ConsumeRowHandler

---

spark/src/main/java/org/datacleaner/spark/RowProcessingFunction.java
spark/src/main/java/org/datacleaner/spark/SparkAnalysisRunner.java

Fixes #571 
This adds a fallback to execution on a single node when non-distributable analyzers are detected in the job.

Feature 571 naive dc spark job coalesce

---

desktop/api/src/main/java/org/datacleaner/widgets/visualization/ComponentScopeButton.java
desktop/api/src/main/java/org/datacleaner/widgets/visualization/ComponentScopeMenuBuilder.java
desktop/api/src/main/java/org/datacleaner/windows/AbstractDialog.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphActions.java
desktop/ui/src/main/java/org/datacleaner/windows/ComponentConfigurationDialog.java
engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
engine/core/src/test/java/org/datacleaner/job/builder/AnalysisJobBuilderTest.java

This adds methods to get the top-level AnalysisJobBuilder as well as all AnalysisJobBuilders.
To make that possible each AnalysisJobBuilder now know its parent, creating a chain of AnalysisJobBuilders.
This is a prerequisite for #570
Change: No longer getting _all_, only getting descendants
Edit: 
Accidentally added the rest of the #570 fix, so if merged, fixes #570.
Please note that there is still a few limitations: Only the default scope will instantly reflect the changes, other scopes will update upon closing the dialog. The scope label does not show which component it comes from, making i.e. several CompletenessAnalyzers will end up with several "Complete rows" scopes and several "Incomplete rows" scopes.
Edit: This should be mergeable, though we have some serious space and …

Possibility to get the top-level builder and all available builders

---

desktop/ui/src/main/java/org/datacleaner/windows/SalesforceDatastoreDialog.java

This makes the Salesforce dialog a little simpler, with no possibility to enter your own endpoint, only a combobox with default or test endpoints. In respecting users with special needs, any externally entered URL will be added to the list.
Fixes #517 
With "normal" endpoints:
With externally configured endpoint

Simplify Salesforce configuration

---

engine/core/src/main/java/org/datacleaner/job/builder/AnalyzerComponentBuilder.java

Fixes #622 
Turned out that this was only an issue when dealing with components that has ```@ColumnProperty(escalateToMultipleJobs=true)``` (typically Value Distribution or Pattern Finder) ... Yet another rare case, but good to have it caught.

Issue #622: Fixed by having special null-logic in setConfiguredProperty

---

desktop/ui/src/main/java/org/datacleaner/panels/MetadataPanel.java
desktop/ui/src/main/java/org/datacleaner/panels/SourceColumnsPanel.java
desktop/ui/src/main/java/org/datacleaner/panels/coalesce/MultipleCoalesceUnitPropertyWidget.java
desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleInputColumnsPropertyWidget.java
desktop/ui/src/main/java/org/datacleaner/widgets/properties/SingleInputColumnComboBoxPropertyWidget.java
desktop/ui/src/main/java/org/datacleaner/widgets/properties/SingleInputColumnRadioButtonPropertyWidget.java
desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
desktop/ui/src/main/java/org/datacleaner/windows/SourceTableConfigurationDialog.java
desktop/ui/src/test/java/org/datacleaner/job/builder/AnalysisJobBuilderTest.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobChangeListener.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalyzerComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/FilterComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java
engine/core/src/test/java/org/datacleaner/job/builder/AnalysisJobBuilderTest.java
pom.xml

This creates a new listener for AnalysisJobBuilder changes, which is used for propagating listeners to newly consumed AnalysisJobBuilders.
Fixes #594 
Fixes #580

Propagate builder listeners

---

monitor/pom.xml
monitor/services/pom.xml
pom.xml

It seems that our configuration of the enforcer plugin used the same id in parent and monitor pom. And unfortunately that means that a few banned dependencies have slipped into our build!
We need to do something about this asap since downstream builds are affected.

Updated the enforcer plugin configurations to catch monitor dependencies

---

desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraph.java
desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java

Fixes #671 
In short: Analyzers are no longer the only type of component that could make a job worth executing, so this PR relaxes some of the feedback you get in the UI about wanting to execute a job under certain circumstances.

Fixed UI's response to non-analyzers adding "executability" to a job

---

api/src/main/java/org/datacleaner/api/AnalyzerResultFutureImpl.java
engine/core/src/main/java/org/datacleaner/job/concurrent/JobCompletionTaskListener.java
engine/core/src/main/java/org/datacleaner/job/runner/ActiveOutputDataStream.java
engine/core/src/main/java/org/datacleaner/util/ConcurrencyUtils.java

This is a small fix to add some logging whenever we are waiting for a long time on CountDownLatches. 
Background: Recently we've seen that the build sometimes stalls in Travis CI ("no output received in 10 minutes"). While I still don't know why that would happen, my guess is that somewhere we maybe have a race condition. And since we call the "normal" CountDownLatch.await() method which blocks infinitely here and there, I thought it would be good to add some logging instead for every 2 minutes that pass by while waiting. That way we gain two things:
* A bit of logging in general on what is happening, why something is not responding.
* Maybe good hints from Travis on where we may have some issues.

Added logging about all CountDownLatch.await() calls in engine and api

---

README.md

This adds a Travis SVG image (and link) that will show the build status of master.

Show Travis build status on front page

---

engine/env/spark/pom.xml
pom.xml

Fixes #707 by removing and banning the apache-log4j-extras dependency.
Please review and ensure that this makes it into the next release.

Removed and banned dependency on apache-log4j-extras

---

components/value-distribution/src/main/java/org/datacleaner/beans/valuedist/SingleValueDistributionResult.java

Fixes #743  
check if there are sample rows for "null" values of value distribution.
The method did not check if there are annotated Rows for null values. 
It returned true and it created an window with no row sample examples.

check if there are sample rows for "null" values of value distribution.

---

desktop/ui/src/main/java/org/datacleaner/panels/SchemaTreePanel.java
desktop/ui/src/main/java/org/datacleaner/widgets/tree/SchemaTree.java

Fixes #758 
In addition to making the search box catch keystrokes from the whole tree panel, I also made the searching more broad because I think it was being too strict before. So now the search is ignoring whitespaces and it searches also aliases and category names. Thus if you search on e.g. 'Text' you get:
Or searching "refere":
I also made it easy to clear the text field by clicking Esc.

Made search work on whole tree panel. Search alias+category.

---

desktop/ui/src/main/java/org/datacleaner/widgets/properties/SingleColumnNamePropertyWidget.java

Fixes #747 
This was basically an issue of making sure that the combobox would accept a column name before it had been instrumented with a table. The order of instrumenting it with the table is out of the property widget's hands.
I also added a fireValueChanged(...) in the end to ensure that UI is updated if the setValue(...) call is coming from the back instead of the front end.

Column name always showing as "none" in Ref. Integrity analyzer dialog

---

desktop/ui/src/main/java/org/datacleaner/windows/ElasticSearchDatastoreDialog.java
engine/core/src/main/java/org/datacleaner/connection/ElasticSearchDatastore.java

This will ensure a user can enable SSL without having a keystore set.
Fixes #688

Enable ElasticSearchDatastore SSL without keystore set

---

desktop/ui/src/main/java/org/datacleaner/util/DragDropUtils.java

Evem though #770 is hard to reproduce, it's stack trace reveals that in some scenarios the JTree path may be null. So I made a null check on that in order to avoid it.
Fixes #770

Issue #770: Fixed

---

desktop/ui/src/main/java/org/datacleaner/panels/fuse/ColumnListMultipleCoalesceUnitPropertyWidget.java
desktop/ui/src/main/java/org/datacleaner/panels/fuse/StreamColumnMatrixMultipleCoalesceUnitPropertyWidget.java
desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleInputColumnsPropertyWidget.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java

This is more of a workaround than a proper fix, but a proper fix is a bit limited by our interface. The main issue is that the property widgets all have their own listeners directly connected to the builders, making it hard to control listeners without yanking the entire dialog window (which is actually still not bullet-proof). A proper fix would probably only allow (or strongly encourage) listeners to listen to their dialog, which would then have a general component listener (also not currently supported) on the component and/or analysisJobListener.
Luckily, only MultipleInputColumnsPropertyWidget seems to have been directly looking at the input from the listener, instead of just updatingfrom the general state, which should make the other TransformerChangeListener-implementing …

Avoid potentially losing lines

---

desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLinkPainter.java

This avoids a situation where an input column could be mapped to an incompatible source by the _Link to..._ feature of the graph UI. This will also map all relevant columns to column that can be escalated to multiple jobs.
Fixes #791

Do not map an irrelevant/incompatible column

---

components/basic-analyzers/src/main/java/org/datacleaner/beans/CompletenessAnalyzer.java
components/basic-analyzers/src/test/java/org/datacleaner/beans/CompletenessAnalyzerTest.java
desktop/ui/src/test/resources/documentation/completeness_analyzer.html
engine/xml-config/src/test/resources/JaxbJobWriterTest-testNameClashInMelonAndDefaultScope.xml
engine/xml-config/src/test/resources/JaxbJobWriterTest-testReadAndWriteOutputDataStreamsJob.xml

Fixes #611 
Here's a screenshot where I am doing analysis only on firstname+lastname, but then following it with processing of jobtitle (an additional field).

Issue #611: Added 'additional output fields' to Completeness Analyzer

---

desktop/ui/src/main/java/org/datacleaner/widgets/FilenameTextField.java

This should make sure FilenameTextField listeners are protected.
Fixes #809

Fix listener loop

---

desktop/api/src/main/java/org/datacleaner/util/HasNameComparator.java
desktop/ui/src/main/java/org/datacleaner/actions/ComponentReferenceDocumentationActionListener.java
desktop/ui/src/main/java/org/datacleaner/documentation/CategoryDocumentationWrapper.java
desktop/ui/src/main/java/org/datacleaner/documentation/ComponentDocumentationBuilder.java
desktop/ui/src/main/java/org/datacleaner/documentation/ComponentDocumentationWrapper.java
desktop/ui/src/main/java/org/datacleaner/documentation/ComponentReferenceDocumentationBuilder.java
desktop/ui/src/main/java/org/datacleaner/documentation/IndexDocumentationBuilder.java
desktop/ui/src/main/java/org/datacleaner/documentation/SuperCategoryDocumentationWrapper.java
desktop/ui/src/main/resources/org/datacleaner/documentation/template_component.html
desktop/ui/src/main/resources/org/datacleaner/documentation/template_index.html
desktop/ui/src/test/java/org/datacleaner/documentation/ComponentReferenceDocumentationBuilderTest.java
desktop/ui/src/test/resources/documentation/completeness_analyzer.html
desktop/ui/src/test/resources/documentation/concatenator.html
desktop/ui/src/test/resources/documentation/equals_filter.html
desktop/ui/src/test/resources/documentation/pattern_finder.html
desktop/ui/src/test/resources/documentation/synonym_lookup.html
desktop/ui/src/test/resources/documentation/table_lookup.html

Here's my suggested fix to have a much better index page in the Component library docs.
Screenshots below:
The super-categories are collapsible:
And here's how a super-category without any sub-categories look like:

Update and prettify to the Component library documentation 'index'

---

components/basic-filters/src/main/java/org/datacleaner/beans/filter/EqualsFilter.java
components/basic-filters/src/test/java/org/datacleaner/beans/filter/EqualsFilterTest.java
desktop/ui/src/main/java/org/datacleaner/panels/equalsfilter/EqualsFilterComponentBuilderPresenterRenderer.java
desktop/ui/src/main/java/org/datacleaner/widgets/FilenameTextField.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLinkPainter.java
desktop/ui/src/test/java/org/datacleaner/job/runner/RowProcessingMetricsImplTest.java
desktop/ui/src/test/resources/documentation/equals_filter.html
engine/core/src/main/java/org/datacleaner/data/MetaModelInputRow.java
engine/core/src/main/java/org/datacleaner/metamodel/datahub/DataHubDataSet.java
engine/env/cluster/src/test/java/org/datacleaner/cluster/ClusterTestHelper.java
monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/TenantInfoController.java
monitor/services/src/test/java/org/datacleaner/monitor/server/components/ComponentInfoTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/components/ComponentListTest.java

This fixes #797 and in general I am quite happy with the change.
BUT I would be lying if I said this PR also didn't have any negative consequences. That would be on compatibility of code that is programmatically using the Equals filter. Basically such code needs to be adapted, as can be seen by the diff. I know we have it in use here and there in commercial editions of DC, so that would need to be updated as well.
The ```@Alias``` on the new enum ensures that at least .analysis.xml files are still backwards compatible. The only non-backward compatible change here is that programmatic instantiation of the component has changed.

Equals filter outcome naming

---

desktop/ui/src/main/java/org/datacleaner/widgets/FilenameTextField.java
desktop/ui/src/main/java/org/datacleaner/widgets/HdfsResourceTextField.java
desktop/ui/src/test/java/org/datacleaner/widgets/FilenameTextFieldTest.java

Fixes #830
This was essentially a mixup from our previous story of refactoring FilenameTextField. This time I made the code a bit more robust by adding some unittests to ensure we don't mess up the listener expectations again.

Fix file resource property widget

---

components/html-rendering/src/test/scala/org/datacleaner/result/html/HtmlAnalysisResultWriterTest.scala
engine/core/src/main/java/org/datacleaner/job/ImmutableOutputDataStreamJob.java
engine/core/src/main/java/org/datacleaner/result/SimpleAnalysisResult.java
engine/core/src/test/java/org/datacleaner/test/full/scenarios/JobWithOutputDataStreamsTest.java

It used to be impossible to serialize jobs with output datastreams, because ImmutableOutputDataStreamJob contains a non-transient reference to AnalysisJob. Making it transient fixes that without breaking the serialized result.
Fixes #842

Make ImmutableOutputDataStreamJob serializable

---

components/basic-analyzers/src/main/java/org/datacleaner/beans/CompletenessAnalyzer.java
components/basic-analyzers/src/test/java/org/datacleaner/beans/CompletenessAnalyzerTest.java

As the CompletenessAnalyzer must always get row annotations for the result to show, we cannot use the shared row annotations.
Fixes #837

Do not use injected RowAnnotations

---

components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
engine/core/src/main/java/org/datacleaner/connection/JsonDatastore.java
engine/core/src/main/java/org/datacleaner/descriptors/AnnotationBasedAnalyzerComponentDescriptor.java
engine/core/src/main/java/org/datacleaner/descriptors/ClasspathScanDescriptorProvider.java
engine/core/src/main/java/org/datacleaner/lifecycle/LifeCycleHelper.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkAnalysisRunner.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java
engine/env/spark/src/main/java/org/datacleaner/spark/functions/AnalyzerResultReduceFunction.java
engine/env/spark/src/main/java/org/datacleaner/spark/functions/RowProcessingFunction.java
engine/env/spark/src/main/java/org/datacleaner/spark/functions/TuplesToTuplesFunction.java
engine/env/spark/src/test/java/org/datacleaner/spark/SparkAnalysisRunnerTest.java
engine/env/spark/src/test/resources/write-job.analysis.xml

Fixes #862, but with a few remarks.
* To make this work I had to do some tricks in the spark module which makes it aware of CreateCsvFileAnalyzer. I would prefer that to have that done in a different manner where the component can do all the work and the spark module just makes available some API for the component to figure out all the details. See #873 for more details. Specifically two things are now managed in Spark which should rather be managed by the component:
* Creation of part-files instead of a single file.
* Writing of CSV header line
* Furthermore I would like to raise the need for a better "is distributable" API than just the ```@Distributable``` annotation. In the case of the "Create CSV file" analyzer the distributable flag is dependent on configuration, specifically …

Spark create CSV file

---

engine/rest-client/src/main/java/org/datacleaner/restclient/RESTClientImpl.java
engine/rest-client/src/test/java/org/datacleaner/restclient/RESTClientImplTest.java

In REST client there is a cache for instances which is implemented by a map. Buggy version contained a map with an Integer as a key which was computed by hashCode() method. This could cause collisions so now SHA-1 is used for key creation.

Bug #858 REST client cache map

---

engine/core/src/main/java/org/datacleaner/util/SecurityUtils.java
engine/core/src/test/java/org/datacleaner/util/SecurityUtilsTest.java

Change of a password reading behavior (from conf.xml).  Encoded value with a prefix and a plain text value are loaded correctly. Encoded value without a prefix is incorrect.

Bug #865 encoded password with prefix

---

desktop/ui/src/main/java/org/datacleaner/cli/CliArguments.java
desktop/ui/src/main/java/org/datacleaner/cli/CliRunner.java
desktop/ui/src/test/java/org/datacleaner/cli/MainTest.java
engine/core/src/main/java/org/datacleaner/configuration/DefaultConfigurationReaderInterceptor.java
engine/core/src/main/java/org/datacleaner/util/InputStreamToPropertiesMapFunc.java
engine/env/spark/src/main/java/org/datacleaner/spark/Main.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java
engine/env/spark/src/main/java/org/datacleaner/spark/functions/CsvParserFunction.java
engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java

Added the ability to specify execution properties and system properties for the job and configuration file loading, when running on Spark.
Since the command line length when running Spark jobs is important to keep low (we have seen issues because of long filenames already) I decided to include this using a properties file instead of specifying all properties on the command line directly.

Spark execution properties

---

.travis.yml
api/src/main/java/org/datacleaner/api/OutputDataStream.java
desktop/api/src/main/java/org/datacleaner/util/WindowSizePreferences.java

This should hopefully make it possible to release DC when a JDK 8 is installed. Currently that fails due to the javadoc linter errors.

Fixed javadoc linter errors (not warnings - but enough to make it pass)

---

components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
engine/core/src/main/java/org/datacleaner/output/csv/CsvOutputWriter.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkAnalysisRunner.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java

Fixes #902
A few optimizations
* Added buffering to the output stream (this did the trick)
* Avoiding needless call to HdfsResource.isExists() - this might save some time because it happens again and again.
* Avoiding re-reading the files on HDFS again and again by saving them as Strings in SparkJobContext instead. This means only the driver program needs to read them.

Spark CSV write speed fixed by buffering and not needlessly checking isExists()

---

desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLinkPainter.java

A user should always see the component dialog when trying to link dialogs, even if there are no columns to map.
Fixes #908

Always show link target component dialog

---

desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLinkPainter.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
engine/core/src/main/java/org/datacleaner/util/LabelUtils.java

Filter requirements are now treated like other components, so a component will have its scope changed if a filter from another scope is linked to it.
This also adds a general confirmation for any scope changes that will destroy user configuration, as well as remove a bit of duplication.
Fixes #909

Try to update scope for filters

---

components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceUnit.java
desktop/api/src/main/java/org/datacleaner/actions/PreviewTransformedDataActionListener.java
desktop/api/src/main/java/org/datacleaner/panels/AbstractComponentBuilderPanel.java
desktop/api/src/main/java/org/datacleaner/panels/TransformerComponentBuilderPanel.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
desktop/ui/src/test/java/org/datacleaner/actions/PreviewTransformedDataActionListenerTest.java
engine/core/src/main/java/org/datacleaner/components/maxrows/MaxRowsFilter.java
engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilderImportHelper.java
engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingConsumerSorter.java

Implements a preview function for transformers in output data streams.
Despite the claimed prerequisite described in #931 - that we should take caution into account with this - I decided to go ahead for now. Upon further thought I guess the caution-taking part can be also added later if it is deemed important. But for now I see that preview of output data streams is becoming more and more natural, especially if we add also the Grouper component (another open PR) then this should "just work".
Fixes #931

Preview output data stream

---

desktop/ui/src/main/java/org/datacleaner/util/DCUncaughtExceptionHandler.java

I've run into this issue a number of times and don't see any way we can "fix" it since it must be burried deep in the JUNG framework.
So instead here's a suggestion to make our "uncaught exception handler" simply ignore it.

Added ignore rule for common JUNG error

---

desktop/api/src/main/java/org/datacleaner/util/NumberDocument.java
desktop/api/src/main/java/org/datacleaner/util/WidgetFactory.java
desktop/ui/src/main/java/org/datacleaner/windows/HdfsServerAddressDialog.java

The issue was caused by the NumberFormat applying grouping (thousand
separator) which then made the FormattedTextField try to submit the
value as e.g. "8,020" instead of "8020". This then caused the
NumberDocument to reject the value and return empty string instead.
Also did a small change to update the default port from 9000 to 8020.

Issue #967: Fixed HDFS port text field

---

engine/env/spark/src/main/java/org/datacleaner/spark/SparkConfigurationReaderInterceptor.java

Fixes #986 
The new setting used here is to keep up to 500 (normal) sample sets of maximum 20 records each (decreased from 500)

Issue #986: Decreased the amount of sample records to store in Spark

---

desktop/api/src/main/java/org/datacleaner/widgets/properties/AbstractPropertyWidget.java
desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleInputColumnsPropertyWidget.java

Fixes #975 
This issue was pretty hard to track down. The effective error was that a Swing component was added with an index to the panel in ```AbstractPropertyWidget``` while that panel did not have as many components in it as the index indicated.
But below that is maybe another issue which I honestly couldn't figure out: Why would that happen? The components of the panel are originally added via the ```updateComponents``` method. This method has some logic in it to strip out "non available columns". A column might be unavailable if it's datatype does not match the property's required type. Another reason something might be unavailable is simply if it is referenced as a property value, but it would not be returned when calling ```AnalysisJobBuilder.getAvailableInputColumn```. In this …

Issue #975: Fixed by ensuring that all reordered columns are added

---

components/writers/src/main/java/org/datacleaner/extension/output/AbstractOutputWriterAnalyzer.java
engine/core/src/main/java/org/datacleaner/connection/DatastoreConnectionImpl.java
engine/core/src/main/java/org/datacleaner/connection/ElasticSearchDatastore.java
engine/core/src/main/java/org/datacleaner/connection/UpdateableDatastoreConnectionImpl.java

This should ensure that we keep the client objects created for ElasticSearch under control - that we don't let them linger but close them once the datastore connection is closed.
__PLEASE AWAIT CONFIRMATION BEFORE MERGING__

Making sure to close the Client object made for ElasticSearch connection

---

desktop/ui/src/main/java/org/datacleaner/panels/SchemaTreePanel.java
desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
engine/core/src/main/java/org/datacleaner/connection/UsageAwareDatastoreConnection.java
engine/core/src/main/java/org/datacleaner/util/UsageAwareCloseable.java

I found that the UI was holding a DatastoreConnection even after closing a job. It turned out that this was because the schema tree holds on to it, even after being hidden.
To find out all this I had to use the UsageAwareCloseable logging mechanisms.

Improved ability to track (log) and release early DatastoreConnections

---

Formatter-Eclipse.xml
desktop/ui/src/main/java/org/datacleaner/guice/DCModuleImpl.java
engine/core/src/main/java/org/datacleaner/configuration/DefaultConfigurationReaderInterceptor.java
engine/core/src/main/java/org/datacleaner/util/HadoopResource.java
engine/core/src/main/java/org/datacleaner/util/SystemProperties.java
engine/core/src/main/java/org/datacleaner/util/convert/ResourceConverter.java
engine/core/src/test/java/org/datacleaner/configuration/DataCleanerConfigurationUpdaterTest.java
engine/env/spark/src/main/java/org/datacleaner/spark/Main.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkConfigurationReaderInterceptor.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java
engine/env/spark/src/main/java/org/datacleaner/spark/functions/RowProcessingFunction.java
engine/env/spark/src/main/java/org/datacleaner/spark/utils/HdfsHelper.java
engine/env/spark/src/main/java/org/datacleaner/spark/utils/ResultFilePathUtils.java
engine/env/spark/src/test/java/org/datacleaner/spark/JobResultPathTest.java
engine/env/spark/src/test/java/org/datacleaner/spark/SparkAnalysisRunnerTest.java
engine/env/spark/src/test/resources/jobProperties/jobAbsolutePath.properties
engine/env/spark/src/test/resources/jobProperties/jobRelativePath.properties

I've been spending most of my day making sure we are compatible with Spark running on MapR (using the MapR 5.0.0 sandbox).
This PR unlocks that capability. It ensures that the new ```HdfsHelper``` is in control at all the important stages where resources/paths are loaded. It also makes HDFS the default scheme to use in the Spark module when parsing resource paths without any scheme defined.

Assemble spark module for mapr compatiblity

---

desktop/api/src/main/java/org/datacleaner/util/WidgetFactory.java

We should use the original whenever possible.

Do not use ES's wrapped Guava Strings class

---

desktop/ui/src/main/java/org/datacleaner/user/DemoConfiguration.java
desktop/ui/src/main/resources/datacleaner-home/jobs/Denormalize order totals and present as stacked area chart.analysis.xml
engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java

Here's a new example job that I wanted to add because it's interesting as an "advanced" use case.
It uses a bit a javascript and the grouper component to wrangle the order data into a format that is plottable by the Stacked Area plot.
Graph:
Result screen:

Added new example job using the grouper and stacked area chart

---

engine/core/src/main/java/org/datacleaner/job/builder/AnalyzerComponentBuilder.java
engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilder.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobWriter.java
engine/xml-config/src/test/resources/JaxbJobWriterTest-file4.xml
engine/xml-config/src/test/resources/JaxbJobWriterTest-file5.xml
engine/xml-config/src/test/resources/JaxbJobWriterTest-file6.xml

Fixes #1030
Finally got around to fix this bug ... The individual components was created because the builder creates many analyzer instances. My approach to solving the bug was to then also instrument each produced analyzer with a "secret" (at least never published) metadata value which the JaxbJobWriter then can use to correlate instances of the same builder and write them under the same ```<analyzer>``` element.
If it passes review, I suggest to also apply this fix to the coming 4.5.4 release.

Issue #1030: Fixes saving of only 1 component when having only 1 builder

---

desktop/api/src/main/java/org/datacleaner/util/LookAndFeelManager.java

Assigned a minimum height to the scrollbar in the analyser result panel. 
Fixes #1040

Fixes #1040

---

api/src/main/java/org/datacleaner/api/InputRow.java
components/basic-transformers/src/main/java/org/datacleaner/beans/numbers/GenerateIdTransformer.java
components/basic-transformers/src/test/java/org/datacleaner/beans/numbers/GenerateIdTransformerTest.java
components/grouper/src/main/java/org/datacleaner/components/group/AbstractRowNumberAwareAggregateBuilder.java
components/grouper/src/main/java/org/datacleaner/components/group/GrouperTransformer.java
engine/core/src/main/java/org/datacleaner/data/AbstractLegacyAwareInputRow.java
engine/core/src/main/java/org/datacleaner/data/MetaModelInputRow.java
engine/core/src/main/java/org/datacleaner/data/MockInputRow.java
engine/core/src/main/java/org/datacleaner/data/TransformedInputRow.java
engine/core/src/main/java/org/datacleaner/job/runner/TransformerConsumer.java
engine/core/src/main/java/org/datacleaner/storage/AbstractRowAnnotationFactory.java
engine/core/src/test/java/org/datacleaner/job/runner/ConsumeRowHandlerTest.java
engine/core/src/test/java/org/datacleaner/job/tasks/ConsumeRowTaskTest.java
monitor/services/src/main/java/org/datacleaner/monitor/server/components/ComponentHandler.java
testware/src/main/java/org/datacleaner/test/MockOutputDataStreamAnalyzer.java

Fixes #954
I should add a few notes to this:
* I first tried something quite ambitious - implementing ```long``` instead of ```int``` more or less everywhere. The important places I identified this was:
* InputRow.getId() (which is what #954 tells about)
* RowAnnotation.getRowCount() (not described in #954)
* RowProcessingMetrics.getExpectedRow() (not described in #954)
* But the above quickly became a nightmare to solve in one go. Especially the RowAnnotation change will have a huge impact. It literally is used in hundreds of places. And it's used a lot in result reducer code where it becomes hard to fix unless you really consider line-by-line or even class-by-class what makes sense to do.
* So I reverted to "just" fixing #954. And here's the result.
* Once it was fixed I saw a lot of …

Issue #954: Fixed

---

monitor/api/src/main/java/org/datacleaner/monitor/configuration/AbstractTenantContext.java
monitor/services/src/main/java/org/datacleaner/monitor/configuration/ComponentStoreImpl.java
monitor/services/src/test/java/org/datacleaner/monitor/configuration/ComponentStoreImplTest.java

Fixes #1074 by using ```getOrCreateFolder(...)``` for crucial folders instead of ```getFolder(...)```

Fixes #1074: Create crucial repository folders automatically.

---

desktop/ui/src/main/java/org/datacleaner/panels/fuse/StreamColumnMatrixMultipleCoalesceUnitPropertyWidget.java

Revert commit 1eeed14a8c1f19b8d2ffe43fe1da093f828ddd98 which had unintended sideeffects, and seems to be a wrong fix to a wider problem (see #1056).
Fixes #1064

Reinstate coalesce update in union refresh

---

components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceUnit.java
components/fuse/src/test/java/org/datacleaner/components/fuse/CoalesceUnitTest.java
engine/core/src/main/java/org/datacleaner/data/MockInputColumn.java
engine/core/src/main/java/org/datacleaner/data/TransformedInputColumn.java

This is the first attempt at making CoalesceUnit use paths instead of names. This avoids clashes between two tables with the same name.
Potential issues:
- Transformed columns may still very much clash
- Dots in names will probably cause problems
- Test test test... And then test some more. We have had many unexpected problems, and while this is a pretty minor change code-wise, the change could have big implications.
Fixes #1056

Make CoalesceUnit path-based for physical columns

---

engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java

While working on testing of a bugfix I ran into the issue that a Transformer's getOutputColumns() method may throw an unexpected exception - and we don't handle that situation today.
This PR does the simplest thing possible: If it happens, it gets logged and no output columns are made available. Maybe we can do better, but since it should be an extremely rare case then it's my suggestion to do like this :)

Added catching of exceptions when Transformer.getOutputColumns() throws

---

desktop/ui/src/test/java/org/datacleaner/actions/PreviewTransformedDataActionListenerTest.java
monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceImpl.java
monitor/services/src/main/java/org/datacleaner/monitor/server/jaxb/SaxExecutionIdentifierReader.java
monitor/services/src/test/java/org/datacleaner/monitor/server/xml/SaxExecutionIdentifierReaderTest.java

I made a small improvement here to ensure that if parsing fails, then the exception includes the file name so that investigation is easier. We recently had this happen for a customer and figuring out what went wrong wasn't very easy ...

Improved exception message when SaxExecutionIdentifierReader fails

---

desktop/api/src/main/java/org/datacleaner/widgets/table/DCTableCellRenderer.java
desktop/api/src/test/java/org/datacleaner/widgets/table/DCTableCellRendererTest.java

Fixes #1079 
The approach was not to go "narrowly" just after the preview source table window, but to take all data sets displayed. To do this I made the fix in the DCTableCellRenderer which is applied to all tables in DC desktop.

Issue #1079: Implemented general purpose CLOB rendering for DCTables

---

components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceMultipleFieldsTransformer.java
desktop/api/src/main/java/org/datacleaner/panels/TransformerComponentBuilderPanel.java
desktop/ui/src/main/java/org/datacleaner/panels/fuse/CoalesceUnitPanel.java

This makes the fuse/coalesce transformer survive column renames. The connections will still be lost, though.
Fixes #1090

Allow column renames of fuse input

---

monitor/services/src/main/java/org/datacleaner/monitor/server/SecureGwtServlet.java

Fixes #1085 
Due to some timing issue the private static Logger would not log the
errors to the log file(it is possible the logger is created too early). Therefore the logger is created when it is needed.

Logging errors in DC monitor

---

desktop/ui/src/main/java/org/datacleaner/windows/CreateTableDialog.java

On a customer engagement today we faced that it is sometimes convenient to be able to remove all columns from the "Create table" dialog. This PR does that:

Added "Remove all columns" button to Create table dialog

---

desktop/ui/src/test/java/org/datacleaner/widgets/properties/PropertyWidgetFactoryTest.java

Added a tearDown method to the TestCase which cleans up the created userpreferences.dat when it's finished.

Fix for PropertyWidgetFactoryTest

---

api/src/main/java/org/datacleaner/reference/DictionaryConnection.java
api/src/main/java/org/datacleaner/reference/SynonymCatalogConnection.java
components/javascript/src/main/java/org/datacleaner/beans/script/JavaScriptTransformer.java
components/reference-data/src/main/java/org/datacleaner/beans/transform/RemoveDictionaryMatchesTransformer.java
components/reference-data/src/main/java/org/datacleaner/beans/transform/SynonymLookupTransformer.java
components/reference-data/src/test/java/org/datacleaner/beans/transform/RemoveDictionaryMatchesTransformerTest.java
components/reference-data/src/test/java/org/datacleaner/beans/transform/SynonymLookupTransformerTest.java
components/reference-data/src/test/resources/synonym-countries.txt
desktop/ui/src/test/java/org/datacleaner/job/runner/MockMonitoredDictionary.java
desktop/ui/src/test/resources/documentation/synonym_lookup.html
engine/core/src/main/java/org/datacleaner/reference/DatastoreDictionaryConnection.java
engine/core/src/main/java/org/datacleaner/reference/DatastoreSynonymCatalogConnection.java
engine/core/src/main/java/org/datacleaner/reference/SimpleDictionary.java
engine/core/src/main/java/org/datacleaner/reference/SimpleSynonymCatalog.java
engine/core/src/test/java/org/datacleaner/reference/SimpleSynonymCatalogTest.java
engine/core/src/test/java/org/datacleaner/reference/TextFileSynonymCatalogTest.java
engine/xml-config/src/test/java/org/datacleaner/configuration/SampleCustomDictionary.java
engine/xml-config/src/test/java/org/datacleaner/configuration/SampleCustomSynonymCatalog.java

This allows spaces in dictionaries and synonym lists for RemoveDictionaryMatches and SynonymLookup transformers.
Fixes #1116

Allow spaces in (some) reference data

---

monitor/services/src/main/java/org/datacleaner/monitor/server/SecureGwtServlet.java
monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/TenantInfoController.java
monitor/services/src/main/java/org/datacleaner/monitor/server/security/TenantCheckFilter.java
monitor/services/src/main/java/org/datacleaner/monitor/server/security/UserBean.java
monitor/services/src/main/java/org/datacleaner/result/renderer/InteractiveWriteDataResultHtmlRenderer.java

Fixes #1107 
After much investigation I finally found out what this was about - that the tenant ID was actually set as null by ```UserBean.updateUser()``` in cases where the UserBean had been deserialized by Tomcat! The way this happened was that TenantResolver was transient and in the ```updateUser``` call there was a "if tenant resolver is null, then tenant ID is null" kind of logic. Now instead we do not keep the tenant resolver in the UserBean, so it should never be null.

Fixes #1107 - resolving tenant ID from serialized User object.

---

desktop/api/src/main/java/org/datacleaner/actions/PreviewTransformedDataActionListener.java
desktop/api/src/main/java/org/datacleaner/panels/TransformerComponentBuilderPanel.java
desktop/ui/src/test/java/org/datacleaner/actions/PreviewTransformedDataActionListenerTest.java
desktop/ui/src/test/resources/benchmark/PreviewTransformedDataActionListenerTest-testFilterWithCoalesce.analysis.xml
desktop/ui/src/test/resources/benchmark/PreviewTransformedDataActionListenerTest-testPreviewTransformationInMultiStreamGeneratedOutputDataStream.analysis.xml
engine/core/src/main/java/org/datacleaner/job/AnalysisJobImmutabilizer.java
engine/core/src/main/java/org/datacleaner/job/CompoundComponentRequirement.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobWriterTest.java
testware/src/main/java/org/datacleaner/test/TestHelper.java

Issue was that max rows filter was added using OR compound filter, meaning that all other filters was essentially nuked (as well as the max rows filter if the other filters has an outcome).
I extended the filter to also support ALL scenario, though it is a bit of weird hybrid now (normally ALL scenario is done by chaining requirements).
For some reason, this does NOT fix the test case, allthough it fixed a manual test in DC (I used the first example Kasper provided in fixed case).
This fix is obviously not mergeable with a broken unit test, but I'd like some feedback to my approach.
Fixes #1047

Fix for preview filter issue.

---

engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteDescriptorProviderImpl.java

If remote components URL is without port, using default port to check the connectivity.

bugfix - remote components URL without port

---

desktop/ui/src/main/java/org/datacleaner/widgets/properties/PropertyWidgetFactoryImpl.java

When you map input columns to an enum type input field using the `@MappedProperty` annotation, the wrong property was rendered, the input columns should be rendered, not the property to which they are mapped.

Wrong property shown for input columns mapped to enum

---

desktop/ui/src/test/resources/benchmark/PreviewTransformedDataActionListenerTest-testPreviewTransformationInMultiStreamGeneratedOutputDataStream.analysis.xml
engine/xml-config/src/test/resources/JaxbJobWriterTest-testReadAndWriteOutputDataStreamsJob.xml
pom.xml

This branch applies the new Apache MetaModel 4.5.1 which is currently _staged_ for release.
A few changes in test benchmark files, but those make sense.
__Do not merge yet__ - the Apache MetaModel release has to finish and then we need to remove the staging repository from ```pom.xml```

Upgraded to MetaModel 4.5.1 and updated test benchmark differences

---

monitor/ui/pom.xml

#1145  
At http://localhost:8888/DataCleaner-monitor/repository/swagger.json there was an exception AbstractMethodError. Problem was in provided dependency in jetty (servlet-api). It means in localhost development mode/environment. New version of jetty-server-all fixed the problem.

AbstractMethodError in swagger JSON controller.

---

desktop/ui/src/main/java/org/datacleaner/windows/TextFileDictionaryDialog.java
engine/core/src/main/java/org/datacleaner/util/FileResolver.java
engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
engine/xml-config/src/test/java/org/datacleaner/configuration/JaxbConfigurationReaderTest.java
engine/xml-config/src/test/resources/example-configuration-reference-data-resource-paths.xml

Fixes #1160 
Actually the solution is not very pretty because it is a file-only (as in - not any other resource types) fix. But it seems to be the minimum-impact resolution of the bug. The more general issue is that loading of dictionary and synonym resource is using the deprecated ```createFilename(...)``` method on the ```ConfigurationReaderInterceptor```.
It would be better (but a separate issue IMO) to use a real resource implementation but that would leak then also into standardizing how we write resource paths in XML (see ```DomConfigurationWriter.toFilename(Resource)``` which only does a partial job at this - candidate for a refactoring I would say).

Issue #1160: Fixed by adding "file://" prefix support in FileResolver

---

engine/remote-components/src/main/java/org/datacleaner/descriptors/AnnotationProxy.java

I encountered this problem in scenario that a Monitor is exposing component that is actually a remote component to another Monitor server. Seems mad, but the bugfix is valid anyway :-)

Repaired the Annotation proxy

---

monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ComponentControllerV1.java

If the developer of extension provides the icon bigger (by accident), it is scaled.

transformer icon returned in a REST api is limited to 32x32

---

components/basic-transformers/src/main/java/org/datacleaner/beans/transform/RemoveUnwantedCharsTransformer.java

Fixes #1153 
RemoveUnwantedCharsTransformer was not declared as a public class. I didn't find the particular reason why package-private classes don't work, but making the class public (as other transformers) solves the problem.

Remove unwanted characters cannot be added to canvas

---

api/src/main/java/org/datacleaner/api/UsageMeteringMessage.java
api/src/test/java/org/datacleaner/api/UsageMeteringMessageTest.java

Previously providing null value in details array caused nothing was added at that position. But we rely on the fields position when analysing the metering message.

Metering message - providing null value in details should be the same as empty string.

---

desktop/ui/pom.xml
monitor/services/pom.xml

While working with the latest master desktop UI I noticed these warnings:
```
ERROR 11:58:45 DCClassVisitor - Failed to load class org.datacleaner.visualization.DensityAnalyzerResultHtmlRenderer because of unsatisfied class dependency: scala/xml/MetaData
ERROR 11:58:45 DCClassVisitor - Failed to load class org.datacleaner.visualization.ScatterAnalyzerResultHtmlRenderer because of unsatisfied class dependency: scala/xml/MetaData
ERROR 11:58:45 DCClassVisitor - Failed to load class org.datacleaner.visualization.StackedAreaAnalyzerResultHtmlRenderer because of unsatisfied class dependency: scala/xml/MetaData
ERROR 11:58:45 DCClassVisitor - Failed to load class org.datacleaner.visualization.DensityAnalyzerResultHtmlRenderer because of unsatisfied class dependency: scala/xml/MetaData
ERROR …
```

Ensured inclusion of scala-xml and scala-library in desktop+monitor

---

desktop/api/src/main/java/org/datacleaner/widgets/ExecuteButtonOptions.java
desktop/ui/src/main/java/org/datacleaner/widgets/ExecuteButtonBuilder.java

Add AnalysisJobBuilderWindow to createActionListener (and run) methods on ExecutionMenuItem interface and abstract SimpleExecutionMenuItem implementation to make it available to custom ExecutionMenuItem implementations (which typically extend SimpleExecutionMenuItem).

Add AnalysisJobBuilderWindow to ExecutionMenuItem methods

---

engine/env/spark/src/main/java/org/datacleaner/spark/ApplicationDriver.java

When you provide a location for the results of the job which is executed on the Hadoop cluster through the SparkLauncher, a temporary properties file is created containing the location for the results. This properties file is then copied to the Hadoop file system, but this doesn't work (and silently fails), because the hdfs path which is created (and to which the properties file is copied) contains the absolute location of the properties file as it has been created on your local machine. This is easily fixed by just adding the properties file name to the hdfs path, instead of its absolute location.

Launching spark job with resultfile URI fails

---

engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java
engine/xml-config/src/test/resources/example-job-job-title-analytics.analysis.xml

Fixes #1196 
Does so by using `<` instead of `!=` when comparing expected vs actual output columns on loading a job. The effect is that it's OK for component authors to add output columns, but not to remove them. A corner case (which also existed before) is if the meaning of an output column is changed - in that case the component developer has (still) buried a hole for himself ;-)

Fixes #1196: Only check there are enough (but not same amount) columns

---

components/basic-transformers/src/main/java/org/datacleaner/beans/transform/TextCaseTransformer.java
components/basic-transformers/src/test/java/org/datacleaner/beans/transform/TextCaseTransformerTest2.java
engine/env/spark/src/main/java/org/datacleaner/spark/utils/HdfsHelper.java

Fixes #1161 . 
I have also added another scope to this story. I have seen that the transformation mode ```CAPITALIZE_WORDS ``` doesn't capitalize the words separated by '-' .  So I fixed that as well.

Fixes #1161 - text cases transformers

---

engine/env/spark/pom.xml

This adds the remote components module to the dependencies of the Spark module.
Fixes #1225

Add remote components to Spark deps

---

desktop/api/src/main/java/org/datacleaner/actions/PreviewSourceDataActionListener.java
desktop/api/src/main/java/org/datacleaner/widgets/table/DCTable.java
desktop/api/src/main/java/org/datacleaner/windows/DataSetWindow.java

Fixes #1191
See #1191 for investigation details.
I also updated the error dialog shown when a DataSetWindow is unable to render. This was to add a little bit of detail around the error (but still referring to the log file for more details).

Fixes #1191 by doing an eager check if displayed TableModel is OK

---

engine/core/src/main/java/org/datacleaner/util/convert/HadoopResourceBuilder.java
engine/core/src/test/java/org/datacleaner/util/convert/HadoopResourceBuilderTest.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkConfigurationReaderInterceptor.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java
engine/env/spark/src/test/java/org/datacleaner/spark/SparkConfigurationReaderInterceptorTest.java

Fixes #1222 
This is a bit of a dirty workaround since it just strips out any Hadoop-resource server definition from HDFS urls on Spark. I couldn't imagine another way to do it that wasn't more or less a complete rewrite of how resources are loaded. The (pretty significant) drawback of this approach is that now you cannot refer to a HDFS resource outside of the cluster that spark is running in. I guess that could be a future use case if someone has multiple Hadoop clusters (for some reason) that need to process data across in the same job?
For the reviewer: Please double check the regex Pattern that I've used. I think it's fine, but please give a second opinion.

#1222 - HDFS resource (with template) loading on Spark

---

desktop/api/src/main/java/org/datacleaner/widgets/table/DCTable.java

The constructor of DCTable was invoking the protected method getCopyMenuItems(). If a derived class overrides getCopyMenuItems(), then the DCtable constructor would thus invoke the getCopyMenuItems() on the derived class before the instance was constructed.
The change moves the call to getCopyMenuItems() to the consumeMouseClick method.
Please review, and hopefully merge. (and you can also add a nice heart emoticon...)

Cdtable fix get menuitems

---

engine/env/spark/src/main/java/org/datacleaner/spark/ApplicationDriver.java

Allows the "primary" JAR of spark to be prefixed with _either_ `DataCleaner-env-spark` or `DataCleaner-spark`

Added multiple possible 'primary' spark JAR filename prefixes

---

engine/core/src/main/java/org/datacleaner/job/builder/AnalyzerComponentBuilder.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java
engine/env/spark/src/test/java/org/datacleaner/spark/SparkAnalysisRunnerTest.java
engine/env/spark/src/test/resources/escalated-job.analysis.xml
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobWriter.java

To avoid escalated component jobs being sent to a single reducer, a new partition index is introduced, which makes it possible to see that the partitions are not the same job.
Fixes #1242

Add new partition index to Spark component key

---

engine/env/spark/src/main/java/org/datacleaner/spark/ApplicationDriver.java
engine/env/spark/src/main/java/org/datacleaner/spark/SparkRunner.java

To support the listener interface, a launch method that returns the Process instead of waiting for it has been added.
Fixes #1253

Add a listener interface to SparkRunner

---

engine/core/src/main/java/org/datacleaner/job/runner/ErrorAwareTaskRunnerWrapper.java
engine/core/src/main/java/org/datacleaner/job/tasks/CloseTaskListener.java
engine/core/src/test/java/org/datacleaner/job/tasks/CloseTaskListenerTest.java

To avoid hangs, closing tasks must always continue, even with an error in a component's `@Close`-annotated methods.
We may want to do more elaborate reporting, but for now an error is just logged.
Fixes #1247

Catch errors in component close methods

---

desktop/ui/src/main/java/org/datacleaner/util/HdfsUtils.java
desktop/ui/src/main/java/org/datacleaner/windows/HdfsUrlChooser.java

Fixes #1150.
Changed the max number of retries for trying to connect with an HDFS to 1 (where the default is 45) when selecting a File from an HDFS and refactored the code a bit, so no more attempts to retrieve files from the HDFS are done if the scanning of the Hadoop config files isn't successful.

Lower timeout for HdfsUrlChooser

---

desktop/api/src/main/java/org/datacleaner/widgets/ExecuteButtonOptions.java

A small (but important) fix to the "Preview N rows" functionality on the execute button. This ensures that ordering is not applied by the "Max rows" filter - which means that on the query execution plan, nothing is done to apply an "ORDER BY" clause.
(I just ran out of memory due to this - because I was previewing a job based on a very big CSV file ... DOH!)

Preventing "ordering" in MaxRowsFilter when "Running on N rows"

---

engine/env/spark/src/main/java/org/datacleaner/spark/SparkConfigurationReaderInterceptor.java
monitor/services/src/main/java/org/datacleaner/monitor/configuration/ConfigurationFactory.java

This avoids a lot of ERROR log statements because certain renderers cannot load in Spark or Monitor environment when desktop-ui is not available.

Removed swing-oriented rendering formats from Spark and Monitor config

---

engine/core/src/main/java/org/datacleaner/util/convert/HadoopResourceBuilder.java
engine/core/src/test/java/org/datacleaner/util/convert/HadoopResourceBuilderTest.java

Fixes #1259
Changed the regular expression so it is able to handle more kinds of names for direct namenode connections to Hadoop clusters.

Hadoop direct namenode connection naming

---

desktop/ui/src/main/java/org/datacleaner/user/DemoConfiguration.java

Fixes #1269.
Replaced reference to non existent "Salesforce dedup training" job with one to the existent "Salesforce duplicate detection" job.

Fix reference to Salesforce duplicate detection job

---

desktop/ui/src/main/resources/datacleaner-home/jobs/Copy employees to customer table.analysis.xml

Fixes #1270.
The JOBTITLE field in the CUSTOMERS table may not be null and therefore a value has to be inserted in it by the job.

Set value for Jobtitle when inserting field in customers table

---

desktop/ui/pom.xml

Fixes #1285.
Copy images/actions/*_dark.png to images/actions/*.png to make sure components compiled against older versions which use the .png files still work at run-time.

Fix errors caused by missing .png files

---

components/basic-transformers/src/main/java/org/datacleaner/beans/transform/PlainSearchReplaceTransformer.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java
engine/xml-config/src/test/resources/version_4_5_3_plain_search_replace.analysis.xml

Fixes #1284.
Added some logic to the JaxbJobReader#applyProperties method which checks if a property has been removed from the component which is being read, stores these values and uses these to process the removed properties, i.e. assign their values to another newly introduced property if necessary.
Implemented this logic specifically for the PlainSearchReplaceTransformer from which the "Search string" and "Replacement string" properties have been removed in favor of a "Replacements" property.

Fix backwards compatibility issue in plain search/replace transformer

---

desktop/ui/src/main/java/org/datacleaner/panels/DataCloudInformationPanel.java
desktop/ui/src/main/java/org/datacleaner/util/MutableRemoteServerConfigurationImpl.java
desktop/ui/src/main/java/org/datacleaner/util/RemoteServersUtils.java
desktop/ui/src/main/java/org/datacleaner/widgets/DataCloudStatusLabel.java
desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
engine/remote-components/src/main/java/org/datacleaner/configuration/RemoteServerConfigurationImpl.java

#1306 
1) Class name won't be contained in error messages.
2) Add button into panel to show option dialog with datacloud credentials.
3) DataCloud Icon must be green immediately after login to datacloud.

#1306 Datacloud status icon improvements.

---

desktop/ui/src/main/java/org/datacleaner/windows/SimpleDictionaryDialog.java

Fixes #1316.
Increase height of Simple dictionary dialog, so it looks as expected when opening it.

Increase height of Simple dictionary dialog

---

monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ComponentControllerV1.java

Icon of a remote transformer being exposed as a remote transformer was not working. Fixed.

Remote^2 transformer icon was not working

---

desktop/ui/src/main/java/org/datacleaner/windows/ElasticSearchDatastoreDialog.java
engine/xml-config/src/main/java/org/datacleaner/configuration/DomConfigurationWriter.java

This will store client connection types (none was remembered, but only REST was affected). Will also disable cluster name for REST clients, as it is not used.
Fixes #1331
Fixes #1311

ElasticSearch: Remember connection type and don't use cluster name

---

monitor/api/src/main/java/org/datacleaner/monitor/scheduling/model/ScheduleDefinition.java
monitor/api/src/main/java/org/datacleaner/monitor/scheduling/model/TriggerType.java
monitor/api/src/main/resources/execution-log.xsd
monitor/api/src/main/resources/schedule.xsd
monitor/services/pom.xml
monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceImpl.java
monitor/services/src/main/java/org/datacleaner/monitor/server/jaxb/JaxbExecutionLogWriter.java
monitor/services/src/main/java/org/datacleaner/monitor/server/jaxb/JaxbScheduleReader.java
monitor/services/src/main/java/org/datacleaner/monitor/server/jaxb/JaxbScheduleWriter.java
monitor/ui/src/main/java/org/datacleaner/monitor/resources/scheduling.css
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/CustomizeSchedulePanel.java
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/CustomizeSchedulePanel.ui.xml
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/ExecutionLogPanel.java
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/JobHistoryPanel.java
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/SchedulePanel.java

Fixes #1329.
Some things which may need special attention when reviewing this pull request:
- The ScheduleServiceImpl now spawns a `org.apache.commons.io.monitor.FileAlterationMonitor` instance on construction, which spawns a monitoring thread in the initialize method. Please check if the implementation doesn't introduce memory leaks or keeps unwanted references to objects.
- The hot folder monitor is quite trigger happy, when a hot folder trigger is added to as a schedule to a job it instantly starts the job for all initial changes it detects, which may be more than one initially. Please test this and provide some feedback whether or not we want to suppress these first time triggers.
- The Customize schedule dialog in DataCleaner monitor starts with a blue paragraph which describes some …

Hot folder monitoring

---

engine/rest-client/src/main/java/org/datacleaner/restclient/Serializator.java
pom.xml

DataCleaner still uses an older version of the com.fasterxml.jackson libraries than metamodel, which can cause problems when testing custom components for DataCleaner during the development process directly from your IDE. Upgrading these libraries to the latest version remedies these problems. By upgrading to the newest version we can also remove a workaround implemented in the org.datacleaner.restclient.Serializator class.
Because the current version of the spark libraries don't work with the newer com.fasterxml.jackson libraries, the spark version also has to be updated.

Upgrade jackson and spark libraries versions

---

desktop/ui/src/main/java/org/datacleaner/widgets/CharSetEncodingComboBox.java

This will and the (euro-supporting version of) EBCDIC encodings to the combobox, and mark them as such.
Fixes #1346

Add EBCDIC encodings to list

---

desktop/ui/src/main/java/org/datacleaner/cli/CliArguments.java
desktop/ui/src/main/java/org/datacleaner/cli/CliRunner.java
desktop/ui/src/test/java/org/datacleaner/cli/MainTest.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java

This makes it possible to override the datastore to a job with by using -ds on the command line.
Fixes #565

Specify replacement datastore from commandline

---

monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceImpl.java

Fixes #1362.
Made it possible to add a properties file in the hot folder (or the folder in which the hot file is located), which is used to override properties in the default configuration to run the job with. By convention the properties file has to have the same name as the job and the .properties extension. So if you have a job named "Analyze customers" the properties files has to be named "Analyze customers.properties".

Read replacement properties file in hot folder

---

desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java

A refresh will make sure that the correct datastore is always shown.
Fixes #1262

Refresh graph when changing datastore

---

monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceImpl.java

Fixes #1369.
If the configured hot folder trigger is a properties file it makes sense to use that file to get the replacement properties from. This makes it possible to trigger multiple jobs at once with the same replacement properties.

If trigger file for monitor job is a properties file use it for replacement properties

---

monitor/services/src/main/java/org/datacleaner/monitor/server/components/ComponentHandlerFactory.java
monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ComponentControllerV1.java

Remote component config has now qualified autowire. Needed by DataCloud so that a "composite" config bean can be defined in application context, refering to other component config beans.
BTW, the default "empty" config already has a name "published-components", this is why I picked the qualifier of that name - to be backward compatible with the current bean name.

Qualified autowire for remote component config 

---

engine/rest-client/src/main/java/org/datacleaner/restclient/ProcessStatelessOutput.java
monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ComponentControllerV1.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/ComponentControllerV1Test.java

Optional parameter now allows to obtain column info in the response of transformer result.
This PR solves this issue: the remote components API - the method to process rows - returns processed rows as a "table" of data. If called by DataCleaner engine, no problem since it uses another API method "getOutputColumns" to get info about output columns.
But when calling the API directly, it could be good to obtain the column info directly in the "processing" call response. This is why I made it possible through an optional request boolean flag. (Default is "false").
Example output with columns info: (BTW, the columns info format is reused from the existing "getOutputColumns" response)
```
{
"rows": [ [ ["hello", "world"] ], [ ["Hi", "Jane"] ] ],
"columns": [
{
"name": "Greeting",
"type": …
```

Remote component API - output columns info in processing response

---

monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/JobsFolderController.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/JobsFolderControllerTest.java
monitor/services/src/test/resources/example_repo/tenant6/conf.xml
monitor/services/src/test/resources/example_repo/tenant6/jobs/concat_job_no_analyzers.analysis.xml
monitor/services/src/test/resources/example_repo/tenant6/jobs/concat_job_no_datastore.analysis.xml
monitor/services/src/test/resources/example_repo/tenant6/jobs/concat_job_short_column_paths.analysis.xml

Fixes #1391 
The API has been improved to filter jobs based on any job metadata property that have a specific value. 
Eg:
`repository/{tenant}/jobs?property=Category&value=enrichment`

Added API for filtering the jobs based on metadata property

---

components/value-distribution/src/main/java/org/datacleaner/beans/valuedist/ValueDistributionAnalyzer.java
desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java

Fixes #1423  
Original reason for this fix was an exception while running job with unconfigured input columns in ValueDistributionAnalyzer. The fix is general, though. Every exception in AnalysisJobBuilderWindowImpl.updateStatusLabel() makes the job un-executable now.

bug/1423 ValueDistributionAnalyzer, unconfigured output, execution enabled

---

monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/JobTriggeringController.java

This makes sure that jobs without a content type and/or body can still use POST to trigger a job execution.
Fixes #1425
We'd probably like this to be tested pretty thoroughly, since it has already slipped through the cracks once.

Allow POST for jobs without specific content type

---

desktop/ui/src/main/java/org/datacleaner/widgets/LicenceAndEditionStatusLabel.java
desktop/ui/src/test/java/org/datacleaner/widgets/LicenceAndEditionStatusLabelTest.java

This reinstates the edition display that was broken by a refactoring of the right-side panel.
Also makes a (very simple) test to ensure it doesn't get broken again by mistake.
Fixes #1463

Reinstates edition display

---

components/basic-transformers/src/main/java/org/datacleaner/beans/transform/TokenizerTransformer.java
components/basic-transformers/src/test/java/org/datacleaner/beans/transform/TokenizerTransformerTest.java
desktop/ui/src/main/java/org/datacleaner/panels/tokenizer/TokenizerJobBuilderPresenter.java

Fixes #1456 
In Tokenizer dialog, when "token target" is ROWS then "number of tokens" field should be disabled. This worked fine while changing "token target" (onChange event) but after the dialog window was reopened it was enabled again. This is now fixed.

#1456 Tokenizer disregards number of tokens when target is ROWS

---

desktop/ui/src/main/java/org/datacleaner/regexswap/RegexSwapDialog.java

Fixes #1475 
RegexSwapDialog: "view online" button was removed because datacleaner.org does not provide "details" page for particular expressions. 
Before
Now

RegexSwapDialog: 'view online' button was removed

---

desktop/api/src/main/java/org/datacleaner/util/WidgetUtils.java

When DataCleaner desktop is unable to display a text using the default font, it falls back to a custom font and logs a message at warning level, which can flood the logs, but isn't really a problem, because it is handled nicely. Therefore lowering verbosity of log message.

Lower verbosity of log message for displaying text using other font

---

monitor/services/src/main/java/org/datacleaner/monitor/server/MetricValueUtils.java

Fixes #1477.
If a Pattern finder analyzer has a Group column configured the getMatchCount() and getPatternCount() methods on the PatternFinderResult class propage an exception because they both invoke the getSingleCrosstab() which is programmed to throw an exception in case a Group column has been configured.
So, do not return metric groups for Patter finder analyzer for which a Group column has been configured. Just log a message that the Pattern finder analyzer doesn't support this.
It would be better if instead of just logging a message we would provide direct feedback to the user in the user interface, but this would require some more refactoring (and time).

Fix adding of timelines with pattern finder analyzer

---

components/grouper/src/main/java/org/datacleaner/components/group/GrouperTransformer.java

Fixes #1509. 
Added a null check before invoking any logic on the aggregationType variable to prevent NullPointerExceptions.

Added null check for aggregation type when getting output data streams

---

components/standardizers/src/main/java/org/datacleaner/beans/standardize/UrlStandardizerTransformer.java
components/standardizers/src/test/java/org/datacleaner/beans/standardize/UrlStandardizerTransformerTest.java

This many issues with the standardizer, but also breaks compatibility a little bit, as it does not add username to host, or fragment to query. I did keep the a field with no path at all as null, as it is not technically filled. I had a bit of a hard time deciding here, so please comment if you disagree.
For the sake of not breaking jobs, the port number is kept a string even though that makes no sense.
Please note that I did a full-file reformat as it is only the same file in name and (intended) function.
Fixes #1490

Use proper parsing instead of non-working homegrown solution

---

components/data-structures/src/main/java/org/datacleaner/beans/datastructures/BuildListTransformer.java
components/javascript/src/main/java/org/datacleaner/beans/script/JavaScriptAdvancedTransformer.java
components/javascript/src/main/java/org/datacleaner/beans/script/JavaScriptFilter.java
components/javascript/src/main/java/org/datacleaner/beans/script/JavaScriptLogger.java
components/javascript/src/main/java/org/datacleaner/beans/script/JavaScriptTransformer.java
monitor/ui/pom.xml

Fixes #552 
In JavaScriptAdvancedTransformer default code there was ```logger.debug(String, String[], String[], String)``` used. The last item was outputCollector which actually provided it's Object.toString() output (not so useful for users anyway). So, it was removed from the debug output and now ```logger.debug(String, String[], String[])``` is used which works fine.

#552 JavaScriptAdvancedTransformer -- default code was unrunnable at Monitor

---

monitor/services/src/main/java/org/datacleaner/monitor/scheduling/SchedulingService.java
monitor/services/src/main/java/org/datacleaner/monitor/scheduling/SchedulingServiceAsync.java
monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceImpl.java
monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceServlet.java
monitor/services/src/main/java/org/datacleaner/monitor/server/listeners/JobModificationEventUpdateSchedulesListener.java
monitor/services/src/test/java/org/datacleaner/monitor/server/SchedulingServiceImplIntegrationTest.java
monitor/ui/src/main/java/org/datacleaner/monitor/Scheduling.gwt.xml
monitor/ui/src/main/webapp/scheduling.xhtml
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/SchedulingOverviewPanel.java
monitor/widgets/src/main/java/org/datacleaner/monitor/wizard/JobWizardController.java

Fixes #1501 
For Scheduling page (listing of jobs) I used lighter version of "getSchedules" where I omitted properties loading. It does not seem to be necessary just for listing and then simple actions (run, delete, show history, ...). 
Time of listing 1000 copies of a simple job was decreased from 26s to 9s.

Many jobs at Monitor -- performance

---

api/src/main/java/org/datacleaner/job/AnalysisJob.java
engine/core/src/main/java/org/datacleaner/job/AnalyzerJobHelper.java
engine/core/src/main/java/org/datacleaner/result/ListResult.java
engine/core/src/test/java/org/datacleaner/job/AnalyzerJobHelperTest.java
monitor/services/src/main/java/org/datacleaner/monitor/server/MetricValueUtils.java
monitor/services/src/test/java/org/datacleaner/monitor/server/MetricValueUtilsTest.java
monitor/services/src/test/resources/multiscope.analysis.xml
testware/src/main/java/org/datacleaner/result/ListResult.java

This will make it possible to add timeline metrics for analyzers from all scopes, not just those in the root scope.
Fixes #1437

Find metrics from analyzers within outputdatastreams as well

---

desktop/api/src/main/java/org/datacleaner/util/IconUtils.java

Allow rendering of custom jobs from DC monitor(they do not have a descriptor)
Fixes #1513

Allow rendering of custom jobs from DC monitor

---

engine/core/src/main/java/org/datacleaner/job/runner/AbstractRowProcessingPublisher.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java

The Union component was pretty badly broken; Components down the line would render metrics using the outer scope's AnalysisJob, and columns with the same not from different tables would end up in the wrong table when job was loaded. This should fix both issues.
Fixes #1540

Use proper AnalysisJob and column names for union

---

engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
engine/core/src/test/java/org/datacleaner/job/builder/InputColumnLinkingTest.java

Fixes #1531.
Made the algorithm which maps an old input column to a new input column a bit less strict to prevent inserting null values when synchronizing dependent values when a transformer's properties are updated.

Improved dependent properties synchronization

---

monitor/ui/src/main/java/org/datacleaner/monitor/dashboard/widgets/DrillToProfilingResultSelectHandler.java
monitor/widgets/src/main/java/org/datacleaner/monitor/resources/shared.css

Fixes #1499 
DCPopupPanel's width was extended from 800px to 950px because of the overflowing text in "Inspect profiling result".

#1499 DCPopupPanel dialog's width was extended

---

desktop/ui/src/main/java/org/datacleaner/windows/ComponentConfigurationDialog.java

The requirements button relevancy is no longer only check on initial creation of the top banner.
Fixes #826

Update requirements button visibility and text on scope change

---

engine/core/src/main/java/org/datacleaner/util/SourceColumnFinder.java

Fixes #1552.
When a job is executed the RowProcessingPublishers class partitions the job into RowProcessingPublishers, part of this is registering the job on a RowProcessingPublishers object. When doing this it uses a SourceColumnFinder to register the relevant columns to a RowProcessingPublishers object. On the SourceColumnFinder the findOriginatingColumns is invoked which goes into a recursion to determine which columns in a job are the "origin" of a given column. The more components the job has the more often this is caused and the deeper the recursion gets.
This pull request fixes this by putting objects for which the originating Columns have been found into an internal cache on the SourceColumnFinder so they don't have to be retrieved more than once. 
I also refactored the signature …

Added caches to SourceColumnFinder to prevent unneccesary recursion

---

desktop/api/src/main/java/org/datacleaner/windows/AbstractDialog.java
desktop/ui/src/main/java/org/datacleaner/widgets/DCFileChooser.java
desktop/ui/src/main/java/org/datacleaner/windows/AboutDialog.java
desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
desktop/ui/src/main/java/org/datacleaner/windows/OptionsDialog.java

Currently uses the result of getDialogWidth, which might be too wide in some instances, though I haven't seen any yet.
Fixes #1519

Set a minimum size for dialogs

---

monitor/ui/src/test/resources/Dockerfile

Fixes #1567 
COPY command in Dockerfile was updated with target file instead of target directory.

#1567 Docker testing build error: Dockerfile COPY command was updated

---

monitor/services/src/test/java/org/datacleaner/monitor/scheduling/quartz/ExecuteJobTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/ExampleFileRepository.java
monitor/services/src/test/java/org/datacleaner/monitor/server/SchedulingServiceImplIntegrationTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/ExecutionLogControllerTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/JobCopyAndDeleteControllerTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/JobModificationControllerTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/JobTriggeringControllerIntegrationTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/RepositoryZipControllerTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/ResultModificationControllerTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/dao/DatastoreDaoImplTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/job/DefaultJobEngineManagerTest.java
monitor/services/src/test/resources/context/application-context.xml

Fixes #1562.
Use a FileRepository which copies the example repo to a real temp dir to prevent IOExceptions when running tests on Windows.

Copy example repo to temp dir in unit tests

---

monitor/ui/src/test/java/org/datacleaner/monitor/AuthenticationIT.java

Fixes #1569 
AuthenticationIT test now uses default authentication in "before" setup which assures that nobody is logged in before the actual testing requests.

#1569 Docker-integration tests: AuthenticationIT problem

---

desktop/api/src/main/java/org/datacleaner/widgets/DescriptorMenuItem.java

Fixes #1581 
Missing icons in a context menu were replaced by a default icon.

#1581 DescriptorMenuItem: missing components' icons

---

desktop/api/src/main/java/org/datacleaner/windows/AbstractWindow.java

Fixes #1579 
setMinimumSize(...) was added in AbstractWindow. 
Now e. g. "preview" window or "analysis result" window can not be shrinked to nothing anymore.

#1579 AbstractWindow: minimal size.

---

components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceUnit.java
components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceUnitMissingColumnException.java
components/fuse/src/main/java/org/datacleaner/components/fuse/FuseStreamsComponent.java
components/fuse/src/test/java/org/datacleaner/components/fuse/CoalesceUnitTest.java
desktop/ui/src/main/java/org/datacleaner/panels/fuse/CoalesceUnitPanel.java
desktop/ui/src/main/java/org/datacleaner/panels/fuse/ColumnListMultipleCoalesceUnitPropertyWidget.java
desktop/ui/src/main/java/org/datacleaner/panels/fuse/StreamColumnMatrixMultipleCoalesceUnitPropertyWidget.java
engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java

This tries to make Fuse/Coalesce and Union components behave a bit better when removing tables. Fuse/Coalesce should no longer throw error as well as update as it should.
Union is also no longer throwing errors, however it will _not_ update until after closing and opening the dialog. A new issue will be created to deal with that.
Fixes #1580

Improve Coalesce and Union behavior when deleting tables

---

desktop/ui/pom.xml
desktop/ui/src/main/resources/datacleaner-home/jobs/Export of Orders data mart.analysis.xml
desktop/ui/src/main/resources/datacleaner-home/jobs/US Customer STATE check.analysis.xml
desktop/ui/src/test/java/org/datacleaner/cli/JobTestHelper.java
desktop/ui/src/test/java/org/datacleaner/cli/SampleJobsIT.java
pom.xml

Fixes #1577.
Adds integration test for the nine sample jobs in DataCleaner which work out of the box. Runs the jobs in the same manner as the Command Line Interface.

Integration tests for sample jobs

---

desktop/ui/src/test/java/org/datacleaner/cli/JobTestHelper.java
desktop/ui/src/test/java/org/datacleaner/cli/SampleJobsIT.java

This makes sure that jobs are using a completely fresh copy of the testing repository for every test, which is independent of both developers DC home, and between tests.
Fixes #1605

Use a temporaryFolder for testing jobs

---

desktop/api/src/main/java/org/datacleaner/wizard/JobWizard.java
desktop/api/src/main/java/org/datacleaner/wizard/JobWizardCallback.java
desktop/api/src/main/java/org/datacleaner/wizard/WizardProvider.java

Fixes #1599.
Add `JobWizard` and `JobWizardCallback` interfaces to DataCleaner to make it possible to add pluggable  wizards which can be used to kick-start jobs to DataCleaner.

Adding JobWizard interfaces

---

monitor/ui/pom.xml
monitor/ui/src/test/java/org/datacleaner/monitor/AuthenticationIT.java
monitor/ui/src/test/java/org/datacleaner/monitor/JobServicesIT.java
pom.xml
testware/pom.xml
testware/src/main/java/org/datacleaner/test/MonitorRestEndpoint.java

This should make it available outside core DC.
Fixes #1607
(Note: Travis might fail with an unrelated issue in desktop-ui. I'll merge master when the #1606 PR has been merged, so we're sure Travis is happy about this)

Move MonitorRestEndpoint to testware

---

engine/core/src/main/java/org/datacleaner/result/CategorizationResult.java

Fixes #1609  
CategorizationResult (e. g. Country standardizer result) does not show the little green button to show the sample rows if there is none available (no empty list anymore).

#1609 CategorizationResult does not show empty sample anymore

---

engine/core/src/main/java/org/datacleaner/connection/ExcelDatastore.java

In case no column names were given, we tried to infer what they would be. Unfortunately that didn't work as expected, instead throw an exception, so we're removing again. This might need rethinking when we're actually going to use that data, but this was only a preparation for the new MM.
Fixes #1617

Stop inferring custom column names

---

testware/src/main/java/org/datacleaner/cli/JobTestHelper.java

Fixes #1614.
Log the output produced by the CLI when the test doesn't produce the expected (number of) resultsets, because it will typically contain a usefull error message in that case.

Log output produced by the CLI when integration test fails

---

desktop/ui/src/main/java/org/datacleaner/windows/SimpleStringPatternDialog.java

Fixes #1385 
New string pattern dialog's legend: 'A' means one letter, not multiple letters.

#1385 The legend in create-string-pattern-dialog was corrected

---

desktop/ui/src/main/java/org/datacleaner/panels/writers/CustomHeaderColumnNamesAnalyzerJobPanel.java
desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleMappedStringsPropertyWidget.java

Fixes #1612 
Changes related to not-updating text fields in MultipleMappedStringsPropertyWidget were reverted because they make text fields not editable.

#1612 Text fields in e. g. CSVWriter are editable again

---

testware/src/main/java/org/datacleaner/cli/JobTestHelper.java

This will always use the temporary repository folder as DATACLEANER_HOME, so that files cannot conflict with developer home and other tests.
Fixes #1627

Set DATACLEANER_HOME to the temp folder

---

monitor/extensions/csv-datastore-wizard/src/main/resources/org/datacleaner/monitor/server/wizard/CsvDatastoreUploadOrExistingFileWizardPage.html
monitor/extensions/excel-datastore-wizard/src/main/resources/org/datacleaner/monitor/server/wizard/ExcelDatastoreUploadOrExistingFileWizardPage.html
monitor/widgets/src/main/java/org/datacleaner/monitor/shared/widgets/FileUploadFunctionHandler.java
monitor/widgets/src/main/java/org/datacleaner/monitor/wizard/AbstractWizardController.java

fixes #1641. fixed uploading of csv(upload without selecting a file)
The upload button is disabled if no file has been selected for uploading. 
The changes can extended to the Excel datastore as well

fixes #1641. fixed uploading of csv(upload without selecting a file)

---

Formatter-Eclipse.xml
monitor/widgets/src/main/java/org/datacleaner/monitor/shared/JavaScriptCallbacks.java

Changed eclipse code formatter so it formats the code more like Intellij does using the IDEA formatter.
Also added a few @formatter:off, @formatter:on annotations for some difficult cases.

Align Eclipse formatter with IntelliJ

---

monitor/services/src/main/java/org/datacleaner/monitor/server/media/FileUploadServlet.java

Fixes #1662 
Monitor's directory for temporary uploaded files was used only if it was created within the same run. Otherwise (if it already existed) it was not used.

#1662 .datacleaner_upload used properly

---

components/basic-transformers/src/main/java/org/datacleaner/beans/transform/TextCaseTransformer.java

Also removes the default dictionaries, which wont work unless we start doing constructor injection.
Fixes #1671
(I'm not sure what that commit message is about. Apparently my brain auto-corrected validation to serialization... Please change as doing squash merge)

Add validation.

---

monitor/services/src/main/java/org/datacleaner/monitor/scheduling/SchedulingService.java
monitor/services/src/main/java/org/datacleaner/monitor/scheduling/SchedulingServiceAsync.java
monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceImpl.java
monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceServlet.java
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/ScheduleData.java
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/ScheduleDataPager.java
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/ScheduleDataPanel.java
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/ScheduleDataProvider.java
monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/SchedulingOverviewPanel.java

Fixes #1645.
Added ScheduleDataPager, which is an extension of GWT's SimplePager used for adding paging functionality to DataCleaner monitor's scheduling page, which shows the deployed jobs.
Implemented an extensions of the FlowPanel class which implements GWT's HasRows and HasData interfaces to be able to use the ScheduleDataPager.

Add paging to monitor's scheduling page

---

engine/core/src/test/java/org/datacleaner/metamodel/datahub/DataHubUpdateBuilderTest.java
monitor/api/src/main/java/org/datacleaner/monitor/scheduling/model/ScheduleDefinitionModel.java
monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/JobsFolderController.java
monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ScheduleDefinitionsController.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/JobsFolderControllerTest.java
monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/ScheduleDefinitionsControllerTest.java
testware/pom.xml

Resolves #1677 
Added an option to the JobsFolderController, so you can directly define a hot folder for a job which is posted to it. Also added a scheduling endpoint which you can use to schedule an existing job so it uses a hot folder.
I didn't add a DELETE option to the new REST endpoint, because deleting a schedule implicitly deletes the scheduled job, which can already be done through a "jobs" REST endpoint.
Next to that I updated the dependency on mockito to the latest version to be able to make use of java 8 lambda expressions in the unit tests.

REST endpoint to schedule job on Monitor with Hot Folder

---

desktop/api/src/main/java/org/datacleaner/util/WidgetFactory.java
desktop/api/src/main/java/org/datacleaner/widgets/DCTaskPaneContainer.java
desktop/ui/src/main/java/org/datacleaner/panels/result/ProgressInformationPanel.java
desktop/ui/src/main/java/org/datacleaner/widgets/tabs/VerticalTabbedPane.java
desktop/ui/src/main/java/org/datacleaner/windows/ResultWindow.java

Resolves #1679 
Job execution page: the progress bar is not any more moved from visible screen by long log output.
Before:
After:

#1679 Job execution progress always visible

---

components/basic-transformers/src/main/java/org/datacleaner/beans/transform/PlainSearchReplaceTransformer.java
components/basic-transformers/src/test/java/org/datacleaner/beans/transform/PlainSearchReplaceTransformerTest.java

Resolves #1684 
PlainSearchReplaceTransformer can work in case-insensitive mode.

#1684 PlainSearchReplaceTransformer case-insensitive mode

---

desktop/ui/src/main/java/org/datacleaner/widgets/Dropzone.java
engine/core/pom.xml
engine/core/src/main/java/org/datacleaner/util/DatastoreCreationUtil.java
monitor/api/src/main/java/org/datacleaner/monitor/job/JobEngine.java
monitor/api/src/main/java/org/datacleaner/monitor/scheduling/model/ScheduleDefinition.java
monitor/services/src/main/java/org/datacleaner/monitor/scheduling/quartz/ExecuteJob.java
monitor/services/src/main/java/org/datacleaner/monitor/server/MonitorJobReader.java
monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceImpl.java
monitor/services/src/main/java/org/datacleaner/monitor/server/job/DataCleanerJobContext.java
monitor/services/src/main/java/org/datacleaner/monitor/server/job/DataCleanerJobContextImpl.java
monitor/services/src/main/java/org/datacleaner/monitor/server/job/DataCleanerJobEngine.java
monitor/ui/src/test/java/org/datacleaner/monitor/JobServicesIT.java

This makes hot folder jobs to execute, even if there is no existing data store.
It also remove the pre-flight testing of hot folder jobs to make sure that errors shows up in the execution log of jobs.
Fixes #1690

Execute hot folder jobs without an existing data store

---

desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleMappedComboBoxPropertyWidget.java

This overrides the `onValuesBatchSelected` method, ensuring that combobox visibility is properly updated on batch updates.
Fixes #1700

Update multimapped combobox visibility

---

desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleMappedComboBoxPropertyWidget.java

Fixes #1702.
The column meanings were retrieved from the ColumnMeaningCollection in an ordered manner and after that assigned in order to an unordered Set implementation. This is changed, so now the are no longer retrieved in an ordered manner, but they are assigned to an ordered Set implementation which is instanctiated with a Comparator which ensures the ordering within the Set.

Ordering of items in MultipleMappedComboBoxPropertyWidget

---

engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java
engine/xml-config/src/test/resources/example-job-variables-ods.analysis.xml

This will pass the overrides along to the output data stream jobs, and redo the override for those.
It would be better to only have the variables global, but that would also require changes to the writer, so for now this it good enough, I think.
Fixes #1705

Override variables inside output data streams

---

monitor/api/src/main/java/org/datacleaner/monitor/scheduling/model/ScheduleDefinition.java
monitor/api/src/main/resources/schedule.xsd

Fixes #1707. 
Add export metrics field and getter and setter to ScheduleDefinition to make it possible to choose whether or not you want the metric of a job execution to be written to disk upon job execution.
Note that we may not want the exporting of metrics to be optional, but just do it by default, in which case this PR isn't needed.

Export metrics options for schedule definition

---

engine/core/src/main/java/org/datacleaner/descriptors/EnumerationValue.java
engine/core/src/test/java/org/datacleaner/descriptors/EnumerationValueTest.java

Fixes #1711.
Instead of trying to instantiate an EnumerationValue object with a null argument just add a null value to the array which is created.

Instantiate EnumerationValue array with null objects

---

engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java

Changed jaxb context as static field to safe its repeated useless and pricy initialization. It is a usual way to re-use it. BTW, marshaller and unmarshaller are not thread safe and cannot be shared in this way.

XML config and job deserialization optimization

---

monitor/api/src/main/java/org/datacleaner/monitor/scheduling/model/ScheduleDefinitionModel.java

Add the option to active metrics export when scheduling jobs from DataCleaner desktop.

Add option to configure metrics export option when scheduling job

---

components/http/src/main/java/org/datacleaner/components/http/HttpRequestTransformer.java

Resolves #1724 
In HttpRequestTransformer you can now use variables in headers.

#1724 HttpRequestTransformer: variables support in headers.

---

pom.xml

This will update to latest stable MetaModel version, 4.6.0.
Fixes #1734

Bump MetaModel to latest stable version, 4.6.0

---

engine/core/src/main/java/org/datacleaner/metamodel/datahub/DataHubRepoConnection.java

To be sure I compared the path engine/core/src/main/java/org/datacleaner/metamodel/datahub - master vs. release/5.1 and it seems to be aligned now.

fixed URLs in DataHub connector according DataHub 9.0

---

engine/xml-config/pom.xml
pom.xml

Fixes #1748 
Seems that cobertura was the culprit here. And in addition to cobertura I felt that we should probably skip checkstyle when `-DskipTests` is set so that it really becomes more of a compile-only style build.

#1748: Skipping cobertura (and other unnecesary stuff) on -DskipTests

---

desktop/ui/src/main/java/org/datacleaner/actions/OpenAnalysisJobActionListener.java
desktop/ui/src/main/java/org/datacleaner/panels/CommunityEditionInformationPanel.java
desktop/ui/src/main/java/org/datacleaner/panels/WelcomePanel.java

Resolves #1756. 
"Compare the editions" button has been removed, "Try professional edition" now leads to https://www.quadient.com/products/quadient-datacleaner#get-started-today. 
Before:
Now:

1756 Links to the prof edition were updated.

---

desktop/api/src/main/java/org/datacleaner/util/WidgetScreenResolutionAdjuster.java

Eh, some corrections to my previous update for High DPI screens. This one it actually looks rather OK on a high DPI screen ;-)
Biggest oversight was the max vs min thing. It meant that a factor of 3 would more or less always be applied to high DPI screen rendering.

Adjusted High DPI thresholds after testing on an actual High DPI screen!

---

pom.xml

I believe this fixes #1768. Although testing it will have to wait for the next release I guess :)

Issue #1768: Don't upload shaded jars to Central repo during release

---

desktop/api/src/main/java/org/datacleaner/widgets/table/DCTable.java
desktop/api/src/main/java/org/datacleaner/windows/QueryWindow.java
desktop/ui/src/main/java/org/datacleaner/widgets/properties/SingleStringPropertyWidget.java

Some minor, but pretty visible tweaks, to the high DPI support:
* The syntax text area's fonts (used in Query windows and e.g. JavaScript or Groovy code editors)
* The editable table's row height. Visible in e.g. transformers' "output columns" table.

Tweaked High DPI rendering of editable tables and syntax textarea

---

desktop/ui/src/main/java/org/datacleaner/panels/WelcomePanel.java

Since datacleaner.org's discussion forum is no longer being exposed in menus or anything like that, I've set up the CE website to host specifically labeled issues as discussion topics. This PR will change the button to route people to the new destination where we can hopefully foster a more sustainable community experience.

Reroute link to CE website's discussion forum

---

desktop/ui/src/assembly/bin/datacleaner.sh

Fixes #1755.
Here's a test case console dump:
```
$ ./datacleaner.sh -ds orderdb -t customers -list columns
Using DATACLEANER_HOME: /c/Users/kasper/git/datacleaner/desktop/ui/target/DataCleaner
Using DATACLEANER_LIB_HOME: /c/Users/kasper/git/datacleaner/desktop/ui/target/DataCleaner
Using DATACLEANER_JAVA_OPTS:  -Xmx1024m
INFO  20:02:21 DataCleanerHome - Initializing DATACLEANER_HOME
INFO  20:02:22 DataCleanerHome - Resolved env. variable DATACLEANER_HOME: C:/Users/kasper/git/datacleaner/desktop/ui/target/DataCleaner
Using default log configuration: jar:file:/C:/Users/kasper/git/DataCleaner/desktop/ui/target/DataCleaner/DataCleaner.jar!/org/datacleaner/log4j-default.xml
Failed to load DataCleaner version from manifest: null
Failed to load DataCleaner version from manifest: null
Columns: …
```

Fixes #1755

---

engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java

Fixes #1777
MutableTable#getColumns returns an unmodifiableList. Therefore wrap it in a local ArrayList, so we can remove columns.

Fix ConcurrentModificationException when closing job with output data stream

---

pom.xml

I actually just wanted to update the MM dependency to 5.0.1 ;-)
But then I came across several dependencies that aren't used anymore. I think these where used in the DC monitor codebase maybe. But I figured it'd be good to weed them out.

MetaModel 5.0.1 and sanitizing of other dependencies

---

desktop/ui/src/main/java/org/datacleaner/connection/DatastoreDescriptors.java
desktop/ui/src/main/java/org/datacleaner/widgets/tree/SortedDefaultMutableTreeModel.java

Tried building DataCleaner using JDK 10 and the compiler (1) doesn't allow one of our casts because of a generalization in the `DefaultMutableTreeNode` class, and (2) made me aware of a wrong key we're using when looking up a key (of wrong type) in a map.

Fix bitrot exposed by JDK 10

---

desktop/ui/pom.xml
desktop/ui/src/main/java/org/datacleaner/connection/DatastoreDescriptors.java
desktop/ui/src/main/java/org/datacleaner/panels/ExtensionPackagesPanel.java
desktop/ui/src/main/java/org/datacleaner/util/GraphUtils.java
desktop/ui/src/main/java/org/datacleaner/widgets/tree/SortedDefaultMutableTreeModel.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraph.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLayoutTransformer.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLinkPainterMousePlugin.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphPreferencesPanel.java
desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphTransformers.java
desktop/ui/src/test/java/org/datacleaner/widgets/properties/MultipleMappedColumnsPropertyWidgetTest.java
pom.xml

This branch extends the branch used in PR #1788 - so please take a look at that one first.
This branch upgrades the JUNG library to the latest release (2.1.1). This release of JUNG now relies on Guava instead of the CERN collections library. Supposedly there are other improvements too, but mostly I just considered it a hygeine update and a chance to consolidate on less common libraries for lambdas etc..

JUNG graph API 2.1.1 upgrade

---

desktop/ui/src/main/java/org/datacleaner/widgets/AbstractResourceTextField.java
desktop/ui/src/main/java/org/datacleaner/widgets/ResourceSelector.java

Now resizing (specially making the window smaller) does not hide the text box used in a file selector:
Fixes #1786

Issue #1786: Improved file textfield's resizing capabilities

---

engine/core/src/main/java/org/datacleaner/util/ws/SimpleServiceSession.java
pom.xml

See https://nvd.nist.gov/vuln/detail/CVE-2018-1314 for details on the vulnerability in the previous versions.

Update hive-jdbc to version 2.3.4, addressing CVE-2018-1314

---

pom.xml

From https://github.com/datacleaner/DataCleaner/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open:
Details
CVE-2018-19360 More information
high severity
Vulnerable versions: >= 2.9.0, < 2.9.8
Patched version: 2.9.8
FasterXML jackson-databind 2.x before 2.9.8 might allow attackers to
have unspecified impact by leveraging failure to block the
axis2-transport-jms class from polymorphic deserialization.
CVE-2018-19361 More information
high severity
Vulnerable versions: >= 2.9.0, < 2.9.8
Patched version: 2.9.8
FasterXML jackson-databind 2.x before 2.9.8 might allow attackers to
have unspecified impact by leveraging failure to block the openjpa class
from polymorphic deserialization.
CVE-2018-19362 More information
high severity
Vulnerable versions: >= 2.9.0, < 2.9.8 …

Fixes vulnerabilities with Jackson versions `>= 2.9.0, < 2.9.8`

---

desktop/ui/src/main/java/org/datacleaner/widgets/tree/SchemaTree.java

Running on Java 11 I see null pointer exceptions when I search the schema tree. It seems that the `getText()` call on JTextField returns null sometimes. This PR fixes our handling of that situation.

Fixed issue where JTextField's value is null (iso. empty) on some JVMs

---

pom.xml

To improve build compatibility.
The ´xml-config´ module failed on my new latest JDK installation. Seems that it requires that the jaxb-runtime is included at build time and this was not explicit in the POM file.

Updated JAXB plugin & version

---

components/html-rendering/pom.xml

This change makes scala-library a compile-time and transitive dependency of the ´html-rendering´ module. I'm not sure why it was "only" a test dependency before, and it breaks on newer setups of JDK/Maven, so it should be fixed.

Make scala-library a compile-time dependency

---

components/visualization/src/test/scala/org/datacleaner/visualization/DensityAnalyzerResultSwingRendererTestApp.scala
components/visualization/src/test/scala/org/datacleaner/visualization/StackedAreaAnalyzerResultSwingRendererTestApp.scala

Again, another thing that seems to fail on newer JDKs... And I guess it's much better to refer to the right class containing ´EXIT_ON_CLOSE´.

Use WindowConstants instead of JFrame for constant ref

---

api/pom.xml
datastores/basic-datastores/pom.xml
datastores/hadoop-datastores/pom.xml
engine/env/spark/pom.xml
engine/utils/pom.xml
pom.xml
testware/pom.xml

Since Apache MetaModel is no longer an active Apache project, I figure that it is better to have our own fork for it that we can maintain when needed. I've created that, and released a first version of it with no real changes from the previous version.
This PR updated DataCleaner to depend on artifacts in the `org.eobjects.metamodel` group instead of `org.apache.metamodel`.

Start using eobjects MetaModel (fork) instead of apache MetaModel

---

desktop/ui/src/main/java/org/datacleaner/regexswap/RegexSwapDialog.java
engine/core/src/main/java/org/datacleaner/reference/regexswap/Category.java
engine/core/src/main/java/org/datacleaner/reference/regexswap/Regex.java
engine/core/src/main/java/org/datacleaner/reference/regexswap/RegexSwapClient.java
engine/core/src/test/java/org/datacleaner/reference/regexswap/RegexSwapClientTest.java

As described and discussed in #1767 - this changes the RegexSwapClient class to use https://datacleaner.github.io/content/regexes.json for fetching regexes instead of the decomissioned old XML endpoints.

Feature #1767 - RegexSwap client reimplementation based on JSON endpoint

---

.github/workflows/maven.yml
api/src/main/java/org/datacleaner/api/ExternalDocumentation.java
components/html-rendering/src/main/java/org/datacleaner/documentation/ComponentDocumentationBuilder.java
components/html-rendering/src/main/java/org/datacleaner/documentation/ComponentDocumentationWrapper.java
components/html-rendering/src/main/java/org/datacleaner/documentation/DocumentationLinkWrapper.java
components/html-rendering/src/main/resources/org/datacleaner/documentation/template_component.html
components/html-rendering/src/test/java/org/datacleaner/documentation/ComponentDocumentationBuilderTest.java
desktop/ui/src/main/java/org/datacleaner/output/datastore/DatastoreOutputUtils.java
desktop/ui/src/test/java/org/datacleaner/documentation/builder/ComponentDocumentationBuilderIntegrationTest.java
desktop/ui/src/test/java/org/datacleaner/windows/OpenAnalysisJobAsTemplateDialogTest.java
pom.xml

slf4j, freemarker, jackson, guava, hadoop, postgresql, h2
Note that a bit of coding was actually needed for the Freemarker upgrade. This was to ensure that annotation/reflection types would have normal getter methods which is required by newer versions of Freemarker it seems.

Various dependency updates

---

desktop/ui/pom.xml
engine/env/spark/pom.xml
pom.xml

Fixing another set of security vulnerabilities by upgading our dependency on the very old Log4j 1.x framework.

Updates to the latest version of Log4j 2.x

---

pom.xml

Seeing as #1903 didn't work (seems we DO have a (transitive) dependency on netty still for Cassandra), this just updates Netty to fix the security vulnerability with it.

Updated Netty to v 4.1.73

---

datastores/hadoop-datastores/pom.xml
engine/xml-config/pom.xml
pom.xml

The tattletale plugin was breaking on my local build (not sure why this didn't happen with our CI build) because of duplicated classes in jar files. We had several JAXB and Activation API jar files, so I consolidated the dependencies and banned every JAR file except the latest jakarta based ones.

Consolidated duplicated Activation and JAXB dependencies

---

engine/xml-config/pom.xml
engine/xml-config/src/main/bindings/bindings-job.xjb
engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbPojoDatastoreAdaptor.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobWriter.java
engine/xml-config/src/main/java/org/datacleaner/util/JaxbValidationEventHandler.java
engine/xml-config/src/test/java/org/datacleaner/configuration/JaxbPojoDatastoreAdaptorTest.java
engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java
pom.xml

As far as I can tell, the root cause for #1913 is that JAXB is missing at runtime on newer Java versions. And that's because we shouldn't be using the old jaxb namespaces, but the new Jakarta based JAXB namespaces. This PR fixes that.

Updated xml-config module to use latest Jakarta JAXB generator
