datacleaner/DataCleaner

- components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraph.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
> Fixes #166

- desktop/ui/src/main/java/org/datacleaner/widgets/PopupButton.java
- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
For now, only used for toolbar menu button, but could potentially be used for all
our popups.
At some point, we probably want to use a ToggleButtonUI for this, but
that needs an DarkUI override, so that'll have to wait.
> Makes a popup button component

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraph.java
> Makes the vertex shape fit the icon.

- components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
- components/writers/src/main/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzer.java
- components/writers/src/test/java/org/datacleaner/extension/output/CreateCsvFileAnalyzerTest.java
- components/writers/src/test/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzerTest.java
> #169 added an option for overwriting the previous file

- desktop/ui/src/main/java/org/datacleaner/cli/CliArguments.java
- desktop/ui/src/test/java/org/datacleaner/cli/CliArgumentsTest.java
> Issue #212: Added "/?", "/usage" and "/help" aliases for -usage

- api/src/main/java/org/datacleaner/api/AnalyzerResultFuture.java
- api/src/main/java/org/datacleaner/api/AnalyzerResultFutureImpl.java
- api/src/test/java/org/datacleaner/api/AnalyzerResultFutureTest.java
- engine/core/src/main/java/org/datacleaner/result/renderer/ToStringFutureTextRenderer.java
- engine/core/src/test/java/org/datacleaner/descriptors/ClasspathScanDescriptorProviderTest.java
- testware/src/main/java/org/datacleaner/result/MockAnalyzerFutureResult.java
- testware/src/main/java/org/datacleaner/test/MockFutureAnalyzer.java
> Issue #229: CLI future aware

- engine/core/src/main/java/org/datacleaner/util/LabelUtils.java
Fixes #201 I hope ... I couldn't reproduce in order to check it
> Remove (AnyComponentRequirement[]) from component labels #201

- desktop/api/src/main/java/org/datacleaner/actions/DisplayOutputWritersAction.java
- desktop/api/src/main/java/org/datacleaner/widgets/DescriptorMenuItem.java
> Issue #242: Fixed.

- desktop/api/src/main/java/org/datacleaner/windows/QueryWindow.java
- desktop/ui/src/main/java/org/datacleaner/panels/DatastorePanel.java
Fixes #241 ... here's a screenshot:
> Fixes #241

- engine/xml-config/pom.xml
- monitor/api/pom.xml
- monitor/pom.xml
- monitor/services/pom.xml
- pom.xml
Just updated a bunch of the dependency versions to 'latest and greatest' versions.
Posting as PR to check that Travis build is passing... :)
> Updated versions on many dependencies

- desktop/api/src/main/java/org/datacleaner/util/WidgetUtils.java
- desktop/ui/src/main/java/org/datacleaner/panels/insertintotable/InsertIntoTableJobBuilderPresenter.java
- desktop/ui/src/main/java/org/datacleaner/panels/updatetable/UpdateTableJobBuilderPresenter.java
- desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleMappedColumnsPropertyWidget.java
- desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleMappedPrefixedColumnsPropertyWidget.java
> Issue #277: Fixed

- desktop/ui/src/main/java/org/datacleaner/windows/AbstractFileBasedDatastoreDialog.java
> Fixes #204 by using the resource reference instead of filename.

- desktop/ui/src/main/java/org/datacleaner/windows/ComponentConfigurationDialog.java
> added a prefered size for the ComponentConfigurationDialog

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
Fixes #206 
Made the component react on mousePressed event and changed the graph to react on mouse released event.
> Right click on canvas issue

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
> Issue #300: Adding support for Cmd + click.

- desktop/api/src/main/java/org/datacleaner/actions/QueryActionListener.java
short name instead.
Fixes #272
> Issue #272: Checking if there is a space in qualified table name and use

- desktop/api/src/main/java/org/datacleaner/actions/DisplayOutputWritersForTransformedDataActionListener.java
Fixes #287
Not entirely sure why the condition size == 0 was there. All of the writers (Staging table, Excel, CSV...) did not pass this condition.
> Issue #287: Relaxing automatic input columns selecting condition.

- desktop/api/src/main/java/org/datacleaner/widgets/DCComboBoxUI.java
- desktop/api/src/main/java/org/datacleaner/widgets/DCListCellRenderer.java
- desktop/ui/src/main/java/org/datacleaner/widgets/DCComboBox.java
This also moves the DCListCellRenderer to API, as it needs to be
available there.
Fixes #306
> Makes DCListCellRenderer the default renderer, and tweaks colors.

- components/writers/src/main/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzer.java
Fixes  #318 
There was no setter so I throw an exception instead.
>  add excel extension to filename

- api/src/main/java/org/datacleaner/metadata/ColumnMeaning.java
- api/src/main/java/org/datacleaner/util/HasAliases.java
- api/src/test/java/org/datacleaner/metadata/ColumnMeaningTest.java
- desktop/ui/src/main/java/org/datacleaner/util/DefaultEnumMatcher.java
- desktop/ui/src/test/java/org/datacleaner/util/DefaultEnumMatcherTest.java
Fixes the "too eager column meaning mapping". See #322.
> Fixes #322

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
> Filters should show the popup on mouse release, not press.

- components/basic-transformers/src/main/java/org/datacleaner/beans/coalesce/CoalesceUnitConverter.java
- components/basic-transformers/src/test/java/org/datacleaner/beans/coalesce/CoalesceUnitConverterTest.java
- engine/core/src/main/java/org/datacleaner/util/convert/DelegatingConverter.java
- engine/core/src/main/java/org/datacleaner/util/convert/SerializationStringEscaper.java
> Escape CoalesceUnitConverter, and make de-/serialization symmetric.

- desktop/ui/src/main/java/org/datacleaner/user/DataCleanerHome.java
user home.
Fixes #344. 
The order to follow before (that is causing the problem):
1) Environmental variable
2) System property
3) Working directory
4) User home directory
Changed to:
1) Environmental variable
2) System property
3) User home directory
Simply speaking, ditched the option to create DataCleaner home directory in the working directory.
> Issue #344: Ditched fallback to working directory, going directly to

- engine/core/src/main/java/org/datacleaner/util/ReflectionUtils.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/DashboardServiceImplTest.java
Fixes the current unittest failure in the build (see Travis).
> Fixed issue with reflection based resolving of metric methods

- api/src/main/java/org/datacleaner/configuration/DataCleanerConfiguration.java
- api/src/main/java/org/datacleaner/configuration/DataCleanerHomeFolder.java
- desktop/ui/src/main/java/org/datacleaner/guice/DCModuleImpl.java
- desktop/ui/src/main/java/org/datacleaner/user/DataCleanerHome.java
- desktop/ui/src/main/java/org/datacleaner/user/DesktopConfigurationReaderInterceptor.java
- engine/core/src/main/java/org/datacleaner/configuration/AnalyzerBeansConfigurationImpl.java
- engine/core/src/main/java/org/datacleaner/configuration/ConfigurationReaderInterceptor.java
- engine/core/src/main/java/org/datacleaner/configuration/DataCleanerConfigurationImpl.java
- engine/core/src/main/java/org/datacleaner/configuration/DataCleanerHomeFolderImpl.java
- engine/core/src/main/java/org/datacleaner/configuration/DefaultConfigurationReaderInterceptor.java
- engine/core/src/main/java/org/datacleaner/configuration/InjectionManagerImpl.java
- engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
- monitor/services/src/main/java/org/datacleaner/monitor/configuration/ConfigurationCache.java
- monitor/services/src/main/java/org/datacleaner/monitor/configuration/MonitorConfigurationReaderInterceptor.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/DashboardServiceImplTest.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/JobCopyAndDeleteControllerTest.java
> Issue 367 - DataCleanerHomeFolder

- components/standardizers/src/main/java/org/datacleaner/util/NamedPattern.java
- components/standardizers/src/test/java/org/datacleaner/util/NamedPatternTest.java
- desktop/ui/src/main/java/org/datacleaner/user/MutableDatastoreCatalog.java
- desktop/ui/src/main/java/org/datacleaner/widgets/database/AbstractDatabaseConnectionPresenter.java
- desktop/ui/src/main/java/org/datacleaner/widgets/database/DatabaseConnectionPresenter.java
- desktop/ui/src/main/java/org/datacleaner/widgets/database/OracleDatabaseConnectionPresenter.java
- desktop/ui/src/main/java/org/datacleaner/widgets/database/SQLServerDatabaseConnectionPresenter.java
- desktop/ui/src/main/java/org/datacleaner/widgets/database/UrlTemplateDatabaseConnectionPresenter.java
- desktop/ui/src/main/java/org/datacleaner/windows/AbstractDatastoreDialog.java
- desktop/ui/src/main/java/org/datacleaner/windows/JdbcDatastoreDialog.java
- engine/core/src/main/java/org/datacleaner/database/DatabaseDriverCatalog.java
> Added more connection parameters for making a better oracle connection

- desktop/ui/src/main/java/org/datacleaner/bootstrap/Bootstrap.java
- desktop/ui/src/main/java/org/datacleaner/cli/CliArguments.java
- desktop/ui/src/main/java/org/datacleaner/windows/AboutDialog.java
- desktop/ui/src/test/java/org/datacleaner/cli/CliArgumentsTest.java
- engine/core/src/main/java/org/datacleaner/Version.java
Fixes #362 
Also made the new "distribution version" available in about dialog:
> Issue #362: Added --version, -version and /version cmd line args

- engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
> Properly identify columns of a table

- desktop/api/src/main/java/org/datacleaner/widgets/ChangeRequirementButton.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLink.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphNodeBuilder.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphTransformers.java
- engine/core/src/main/java/org/datacleaner/job/CompoundComponentRequirement.java
First part of #159 - the job graph visualization part. Still the story needs ability to make/modify compound requirements somehow to be complete.
Following is a screenshot of a compound requirement (that was made "in hand" in the .analysis.xml file):
The compound requirement is OR based ... is that communicated in the graph? can we improve that any way?
> Made visualization of compound requirements work

- engine/core/src/main/java/org/datacleaner/result/renderer/RendererFactory.java
- engine/core/src/main/java/org/datacleaner/util/ReflectionUtils.java
- engine/core/src/test/java/org/datacleaner/util/ReflectionUtilsTest.java
Updated ReflectionUtils.getHierarchyDistance() to support mix of class and interface hierarchy distance.
> Fix for reflection issue with renderer selection

- api/src/main/java/org/datacleaner/descriptors/ValidateMethodDescriptor.java
- desktop/ui/src/main/java/org/datacleaner/actions/SaveAnalysisJobActionListener.java
- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
- engine/core/src/main/java/org/datacleaner/descriptors/AbstractMethodDescriptor.java
- engine/core/src/main/java/org/datacleaner/job/ComponentConfigurationException.java
- engine/core/src/main/java/org/datacleaner/job/ComponentValidationException.java
- engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
- engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
- engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilder.java
- engine/core/src/main/java/org/datacleaner/job/builder/NoResultProducingComponentsException.java
- engine/core/src/main/java/org/datacleaner/job/builder/UnconfiguredConfiguredPropertyException.java
> Issue #370: Improved exception hierarchy+handling in validation cases.

- components/pattern-finder/src/main/java/org/datacleaner/beans/stringpattern/DefaultPatternFinder.java
- components/pattern-finder/src/main/java/org/datacleaner/beans/stringpattern/PatternFinder.java
- components/pattern-finder/src/main/java/org/datacleaner/beans/stringpattern/TokenPattern.java
- components/pattern-finder/src/test/java/org/datacleaner/beans/stringpattern/PatternFinderResultHtmlRendererTest.java
- desktop/ui/src/test/java/org/datacleaner/test/full/scenarios/PatternFinderAndStringAnalyzerDrillToDetailTest.java
Fixes #397
... Let's have Travis verify it before we merge :-)
> Issue #397: Replaced locking with concurrent data structures

- desktop/ui/src/main/java/org/datacleaner/actions/ComponentReferenceDocumentationActionListener.java
- desktop/ui/src/main/java/org/datacleaner/widgets/tree/ComponentDescriptorMouseListener.java
- desktop/ui/src/main/resources/org/datacleaner/documentation/template.html
- desktop/ui/src/test/resources/documentation/completeness_analyzer.html
- desktop/ui/src/test/resources/documentation/concatenator.html
- desktop/ui/src/test/resources/documentation/equals_filter.html
- desktop/ui/src/test/resources/documentation/pattern_finder.html
- desktop/ui/src/test/resources/documentation/table_lookup.html
> Issue #395: Added context menu "Component description" to library

- engine/core/src/main/java/org/datacleaner/job/runner/AbstractRowProcessingConsumer.java
- engine/core/src/test/java/org/datacleaner/test/full/scenarios/CompoundComponentRequirementRejectionStreetTest.java
- engine/core/src/test/java/org/datacleaner/test/full/scenarios/FilterRequirementMergingTest.java
- engine/core/src/test/java/org/datacleaner/test/mock/EvenOddFilter.java
> Correction to filtering with OR/Compound filter requirements

- desktop/api/src/main/java/org/datacleaner/actions/PreviewTransformedDataActionListener.java
> Fixes #407

- components/basic-transformers/src/main/java/org/datacleaner/beans/numbers/GenerateIdTransformer.java
- components/basic-transformers/src/test/java/org/datacleaner/beans/numbers/GenerateIdTransformerTest.java
> GenerateIdTransformer with SEQUENCE and ROWID modes.

- components/data-structures/src/test/java/org/datacleaner/beans/datastructures/DataStructuresIntegrationTest.java
- components/javascript/src/test/java/org/datacleaner/beans/script/JavaScriptAdvancedTransformerTest.java
- components/writers/src/test/java/org/datacleaner/beans/writers/InsertIntoTableAnalyzerTest.java
- engine/core/src/main/java/org/datacleaner/job/concurrent/JobCompletionTaskListener.java
- engine/core/src/main/java/org/datacleaner/job/runner/AnalysisListener.java
- engine/core/src/main/java/org/datacleaner/job/runner/AnalysisListenerAdaptor.java
- engine/core/src/main/java/org/datacleaner/job/runner/AnalysisRunnerJobDelegate.java
- engine/core/src/main/java/org/datacleaner/job/runner/CompositeAnalysisListener.java
- engine/core/src/main/java/org/datacleaner/job/runner/InfoLoggingAnalysisListener.java
- engine/core/src/main/java/org/datacleaner/job/runner/RowConsumerTaskListener.java
- engine/core/src/test/java/org/datacleaner/descriptors/ClasspathScanDescriptorProviderTest.java
- engine/core/src/test/java/org/datacleaner/test/TestEnvironment.java
- engine/core/src/test/java/org/datacleaner/test/full/scenarios/AnalyzerResultFutureAndAnalysisListenerTest.java
- engine/core/src/test/java/org/datacleaner/test/full/scenarios/CancellationAndMultiThreadingTest.java
- engine/core/src/test/java/org/datacleaner/util/batch/BatchTransformerTest.java
- engine/env/cluster/src/main/java/org/datacleaner/cluster/DistributedAnalysisResultReducer.java
- engine/env/cluster/src/main/java/org/datacleaner/cluster/DistributedAnalysisRunner.java
Made this PR with things from #421 that are not entirely related to the resolution of #224 (but quite convenient in order to fix it anyway).
> Added various improvements from #421 that are slightly unrelated.

- api/src/main/java/org/datacleaner/api/ExternalDocumentation.java
- components/basic-transformers/src/main/java/org/datacleaner/beans/transform/RegexParserTransformer.java
- components/i18n/src/main/java/org/datacleaner/beans/CharacterSetDistributionAnalyzer.java
- components/i18n/src/main/java/org/datacleaner/beans/TransliterateTransformer.java
- components/pattern-finder/src/main/java/org/datacleaner/beans/stringpattern/PatternFinderAnalyzer.java
- components/reference-data/src/main/java/org/datacleaner/beans/transform/RemoveDictionaryMatchesTransformer.java
- components/reference-data/src/main/java/org/datacleaner/beans/transform/SynonymLookupTransformer.java
- components/value-distribution/src/main/java/org/datacleaner/beans/valuedist/ValueDistributionAnalyzer.java
As part of #395 I added a new annotation for external documentation.
And I put video links to various components.
Questions for reviewer:
* Do you like the API suggested here?
* Any other documentation types we should support now?
* Any special links that come to mind?
> Issue #395: Added @ExternalDocumentation annotation 

- monitor/services/src/main/java/org/datacleaner/monitor/configuration/SharedDescriptorProvider.java
I've been lacking classes from this package in testing scenarios.
> Add org.datacleaner.components to hardcoded values in test scenarios.

- engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
- engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java
- engine/xml-config/src/test/resources/example-job-chain-of-filters.xml
> Issue #452: Fixed reading of analysis.xml files with chained filters

- engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
Refactored the JaxbJobReader to have more isolated methods and to reuse methods for component initialization
Following previous comments that this class is hard to read and has too long methods. I think this helps a lot. Also managed to reuse a lot of stuff around (generic) component initialization instead of having special treatment for filters, analyzers and transformers.
> JaxbJobReader refactor

- pom.xml
Pretty trivial PR, but I wanted to just make sure Travis is happy with the change etc. before pushing to master :-)
> Upgraded to MetaModel 4.3.4 (just released)

- engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobWriter.java
- engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobWriterTest.java
- engine/xml-config/src/test/resources/JaxbJobWriterTest-file1.xml
- engine/xml-config/src/test/resources/JaxbJobWriterTest-file2.xml
- engine/xml-config/src/test/resources/JaxbJobWriterTest-file3.xml
- engine/xml-config/src/test/resources/JaxbJobWriterTest-file4.xml
- engine/xml-config/src/test/resources/JaxbJobWriterTest-file5.xml
- engine/xml-config/src/test/resources/JaxbJobWriterTest-file6.xml
- engine/xml-config/src/test/resources/JaxbJobWriterTest-testReadAndWriteAnyComponentRequirementJob.xml
- engine/xml-config/src/test/resources/JaxbJobWriterTest-testReadAndWriteCompoundComponentRequirementJob.xml
> Issue #464: Introduced more meaningful column-id generation scheme

- api/src/main/java/org/datacleaner/job/ComponentJob.java
- api/src/main/java/org/datacleaner/job/OutputDataStreamJob.java
- api/src/main/java/org/datacleaner/job/OutputDataStreamJobSource.java
- engine/core/src/main/java/org/datacleaner/job/AnalysisJobImmutabilizer.java
- engine/core/src/main/java/org/datacleaner/job/ImmutableAnalyzerJob.java
- engine/core/src/main/java/org/datacleaner/job/ImmutableComponentJob.java
- engine/core/src/main/java/org/datacleaner/job/ImmutableFilterJob.java
- engine/core/src/main/java/org/datacleaner/job/ImmutableOutputDataStreamJob.java
- engine/core/src/main/java/org/datacleaner/job/ImmutableTransformerJob.java
- engine/core/src/main/java/org/datacleaner/job/builder/LazyOutputDataStreamJob.java
- engine/core/src/test/java/org/datacleaner/job/ImmutableFilterJobTest.java
- monitor/services/src/main/java/org/datacleaner/descriptors/PlaceholderComponentJob.java
- monitor/services/src/main/java/org/datacleaner/monitor/configuration/PlaceholderAnalysisJob.java
An attempt to cut #421 into smaller reviewable bits. This one is just about the ComponentJob interface and quite related classes.
> Issue #224: Added the change to ComponentJob interface and related bits

- components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
- engine/core/src/main/java/org/datacleaner/output/csv/CsvOutputWriterFactory.java
> NPE when writing CSV file

- components/writers/src/main/java/org/datacleaner/beans/writers/UpdateTableAnalyzer.java
- desktop/api/src/main/java/org/datacleaner/actions/DisplayOutputWritersForTransformedDataActionListener.java
> Fix for clicking "Write to" -> "Update table"

- desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleInputColumnsPropertyWidget.java
- engine/core/src/main/java/org/datacleaner/result/AnnotatedRowsResult.java
> Excluded hidden columns from "select all" & drill-to-detail windows.

- desktop/ui/src/main/java/org/datacleaner/windows/ResultWindow.java
- engine/core/src/main/java/org/datacleaner/util/LabelUtils.java
Fixes #468 . Instead of the previous PR. Three times is a charm or something.
> Made labels in the result screen use the hasLabelAdvice interface. 

- desktop/ui/src/main/java/org/datacleaner/panels/insertintotable/InsertIntoTableJobBuilderPresenter.java
- desktop/ui/src/main/java/org/datacleaner/panels/tablelookup/TableLookupJobBuilderPresenter.java
- desktop/ui/src/main/java/org/datacleaner/panels/updatetable/UpdateTableJobBuilderPresenter.java
- desktop/ui/src/main/java/org/datacleaner/widgets/properties/PropertyWidgetFactoryImpl.java
- desktop/ui/src/main/java/org/datacleaner/widgets/properties/SchemaNamePropertyWidget.java
- desktop/ui/src/main/java/org/datacleaner/widgets/properties/SingleTableNamePropertyWidget.java
- desktop/ui/src/main/java/org/datacleaner/widgets/tree/SchemaMouseListener.java
- desktop/ui/src/main/java/org/datacleaner/windows/CreateTableDialog.java
- desktop/ui/src/test/java/org/datacleaner/widgets/properties/TableNamePropertyWidgetTest.java
> Made it possible to create tables from the "table name" property widget

- engine/core/src/main/java/org/datacleaner/configuration/InjectionManagerImpl.java
- engine/core/src/main/java/org/datacleaner/job/runner/ComponentContextImpl.java
> Guice provision error in WARN logs fix

- components/standardizers/src/main/java/org/datacleaner/beans/standardize/CountryStandardizationResult.java
- components/standardizers/src/main/java/org/datacleaner/beans/standardize/CountryStandardizationTransformer.java
> Counts all unrecognized countries and adds them to the result.

- engine/core/src/main/java/org/datacleaner/configuration/DefaultConfigurationReaderInterceptor.java
- engine/core/src/main/java/org/datacleaner/util/ExtensionFilter.java
- engine/core/src/main/java/org/datacleaner/util/convert/HdfsResourceTypeHandler.java
- engine/core/src/main/java/org/datacleaner/util/convert/ResourceConverter.java
- engine/core/src/test/java/org/datacleaner/util/convert/HdfsResourceTypeHandlerTest.java
- pom.xml
This is a part of #495 - it will add HDFS support to CSV datastore and other when configured via conf.xml or programmatically.
> HdfsResource in engine of DC

- components/standardizers/src/main/java/org/datacleaner/beans/standardize/Country.java
- components/standardizers/src/main/java/org/datacleaner/beans/standardize/CountryStandardizationTransformer.java
> Issue #396: Added country output format names

- desktop/ui/src/main/java/org/datacleaner/windows/SalesforceDatastoreDialog.java
- engine/core/src/main/java/org/datacleaner/connection/SalesforceDatastore.java
- engine/xml-config/src/main/java/org/datacleaner/configuration/DatastoreXmlExternalizer.java
- engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
- engine/xml-config/src/main/resources/configuration.xsd
> Issue #500: Added custom endpoint url option to SFDC datastore

- components/standardizers/src/main/java/org/datacleaner/beans/standardize/Country.java
Fixes https://github.com/NCIM/online-service-wizard/issues/2144
> Added dutch translations for EU and large countries

- desktop/ui/src/main/java/org/datacleaner/windows/ResultWindow.java
> Sorting analyzers before other components in the ResultWindow tabs.

- engine/core/src/main/java/org/datacleaner/job/runner/ActiveOutputDataStream.java
- engine/core/src/main/java/org/datacleaner/job/tasks/InitializeTask.java
- engine/core/src/test/java/org/datacleaner/test/full/scenarios/JobWithOutputDataStreamsTest.java
> Use OutputDataStream table for OutputRowDataStreamRowCollector.

- desktop/ui/src/main/java/org/datacleaner/panels/result/ProgressInformationPanel.java
- desktop/ui/src/main/java/org/datacleaner/panels/result/TableProgressInformationPanel.java
> Progress bar fix

- api/src/main/java/org/datacleaner/job/output/OutputDataStreamBuilderImpl.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLinkPainter.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLinkPainterMousePlugin.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
- engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
- engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
- engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilder.java
This makes it possible to link a component that has an outputdatastream to other components. This is in no way a complete implementation of ways to link (i.e. it is not possible to link a component using the column list).
Fixes #519
> Implements linking of outputdatastreams in the ui

- desktop/ui/src/main/java/org/datacleaner/windows/AbstractDatastoreDialog.java
Oh man, the complexity of this patch ;-)
Fixes #568
> Use "Register datastore" phrase

- engine/core/src/main/java/org/datacleaner/job/builder/AnalyzerComponentBuilder.java
- engine/core/src/test/java/org/datacleaner/job/builder/AbstractComponentBuilderTest.java
- testware/src/main/java/org/datacleaner/test/MockJobEscalatingAnalyzer.java
> Fixes #574

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphNodeBuilder.java
> Fixes #579 by having a dynamic factory of job graph elements

- api/src/main/java/org/datacleaner/repository/RepositoryFile.java
- api/src/main/java/org/datacleaner/repository/RepositoryFileResource.java
- api/src/test/java/org/datacleaner/repository/RepositoryFileResourceTest.java
- components/uniqueness/src/main/java/org/datacleaner/beans/uniqueness/UniqueKeyCheckAnalyzer.java
- components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
- components/writers/src/main/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzer.java
- components/writers/src/test/java/org/datacleaner/extension/output/CreateCsvFileAnalyzerTest.java
- engine/core/src/main/java/org/datacleaner/output/csv/CsvOutputRow.java
- engine/core/src/main/java/org/datacleaner/output/csv/CsvOutputWriter.java
- engine/core/src/main/java/org/datacleaner/output/csv/CsvOutputWriterFactory.java
- engine/core/src/main/java/org/datacleaner/repository/file/FileRepositoryFile.java
- engine/core/src/main/java/org/datacleaner/util/VfsResource.java
- engine/core/src/main/java/org/datacleaner/util/sort/SortMergeWriter.java
- engine/core/src/test/java/org/datacleaner/util/sort/SortMergeWriterTest.java
- pom.xml
> Write CSV resource

- engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobWriter.java
- engine/xml-config/src/test/resources/JaxbJobWriterTest-testReadAndWriteOutputDataStreamsJob.xml
> Issue #582: Avoid writing job-metadata for output data streams

- spark/src/main/java/org/datacleaner/spark/SkipHeaderLineFunction.java
- spark/src/main/java/org/datacleaner/spark/SparkAnalysisRunner.java
- spark/src/main/java/org/datacleaner/spark/functions/ValuesToInputRowFunction.java
- spark/src/test/java/org/datacleaner/spark/SparkAnalysisRunnerTest.java
> Skip header lines of CSV files in Spark module

- api/src/main/java/org/datacleaner/api/OutputDataStream.java
- engine/core/src/main/java/org/datacleaner/job/runner/AnalysisJobMetricsImpl.java
- engine/core/src/main/java/org/datacleaner/job/runner/ConsumeRowHandler.java
- engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingPublisher.java
- engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingPublishers.java
- engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingStream.java
- engine/core/src/main/java/org/datacleaner/job/tasks/CloseTaskListener.java
- engine/core/src/test/java/org/datacleaner/test/full/scenarios/MultipleChainsOfOutputDataStreamsTest.java
- engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobReaderTest.java
- testware/src/main/java/org/datacleaner/test/MockOutputDataStreamAnalyzer.java
Fixes #583 by introducing an identifyable "RowProcessingStream" to hold Table and AnalysisJob
> Long(er) chains of output data streams

- desktop/ui/pom.xml
- monitor/pom.xml
- monitor/services/pom.xml
- pom.xml
Fixes #602 
Manually verified by using the CSV datastore dialog's preview table
> Fixed javax.servlet.Filter dependency

- desktop/ui/src/main/java/org/datacleaner/widgets/FilenameTextField.java
> Fixed listener callback event in FilenameTextField

- desktop/api/src/main/java/org/datacleaner/panels/TransformerComponentBuilderPanel.java
- engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
> Hiding preview button for child-job transformers

- api/src/main/java/org/datacleaner/job/output/OutputDataStreamBuilder.java
- api/src/main/java/org/datacleaner/job/output/OutputDataStreamBuilderImpl.java
- components/basic-analyzers/src/main/java/org/datacleaner/beans/CompletenessAnalyzer.java
- engine/core/src/test/java/org/datacleaner/connection/UsageAwareDatastoreConnectionTest.java
Added a few convenience methods to easily add columns to an output data stream that are similar to other columns.
> OutputDataStreamBuilder convenience method addition

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphNodeBuilder.java
- engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
- engine/core/src/test/java/org/datacleaner/job/builder/AbstractComponentBuilderTest.java
- testware/src/main/java/org/datacleaner/test/MockDynamicOutputDataStreamAnalyzer.java
Fixes #616 
~~I think this also fixes issue #622 but would like to ask @tomaszguzialek to verify that.~~
> Tolerant outputdatastream changes

- components/value-distribution/.gitignore
- components/value-distribution/src/main/java/org/datacleaner/beans/valuedist/SingleValueDistributionResult.java
- components/value-distribution/src/main/java/org/datacleaner/beans/valuedist/ValueDistributionAnalyzer.java
- components/value-distribution/src/main/java/org/datacleaner/beans/valuedist/ValueDistributionGroup.java
- components/value-distribution/src/test/java/org/datacleaner/beans/valuedist/ValueDistributionAnalyzerTest.java
- components/value-distribution/src/test/scala/org/datacleaner/beans/valuedist/ValueDistributionResultHtmlRendererTest.scala
- desktop/ui/src/main/java/org/datacleaner/documentation/ComponentDocumentationBuilder.java
- desktop/ui/src/main/java/org/datacleaner/widgets/properties/PropertyWidgetFactoryImpl.java
- desktop/ui/src/test/java/org/datacleaner/widgets/result/ValueDistributionResultSwingRendererGroupDelegateTest.java
> Value distribution drill button showing when there's no sample set

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphMouseListener.java
> Issue #641: Fixed

- engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobWriter.java
- engine/xml-config/src/test/java/org/datacleaner/job/JaxbJobWriterTest.java
- engine/xml-config/src/test/resources/JaxbJobWriterTest-testNameClashInMelonAndDefaultScope.xml
- engine/xml-config/src/test/resources/JaxbJobWriterTest-testReadAndWriteOutputDataStreamsJob.xml
> Column IDs unique between scopes

- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
> Pressing "Esc" key now behaves like Cancel button. fixes #656

- monitor/services/pom.xml
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/doc/SwaggerConfig.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/doc/WadlController.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/doc/SwaggerConfigTest.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/doc/WadlControllerTest.java
- monitor/ui/pom.xml
This pull request contains a Swagger controller and it's simple web application (human readable user documentation) and a WADL controller (XML documentation).
> REST documentation

- components/reference-data/src/main/java/org/datacleaner/beans/ReferenceDataMatcherAnalyzer.java
> fix for NPE reference data matching

- engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobWriter.java
Fixes #696 which caused only analyzers to have their output data streams serialized.
> Applying output data streams of all component types

- desktop/api/src/main/java/org/datacleaner/panels/AbstractComponentBuilderPanel.java
- engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
This fixes an update-issue that I identified while working on #620, but since it was independent of #620 I decided to post it here.
> Fixed issues with updating OutputDataStream definitions in UI

- engine/core/src/main/java/org/datacleaner/components/categories/NationalIdentifiersCategory.java
- engine/core/src/main/java/org/datacleaner/components/categories/ProductDataCategory.java
This will move the previous commercial-only categories to community.
> Categories in main DataCleaner

- desktop/ui/pom.xml
- desktop/ui/tattletale-filters.properties
- engine/env/cluster/pom.xml
- engine/env/spark/pom.xml
- monitor/documentation/pom.xml
- monitor/pom.xml
- monitor/ui/pom.xml
- monitor/ui/tattletale-filters.properties
- pom.xml
- standard-components/pom.xml
This PR builds further on top of #708, so maybe merge that one first :)
Fixes #709
> Dependency cleanup with tattletale

- components/standard-components/pom.xml
- desktop/ui/pom.xml
> added the missing components from standard components module 

- engine/core/src/main/java/org/datacleaner/job/runner/AbstractRowProcessingPublisher.java
- engine/core/src/main/java/org/datacleaner/job/runner/OutputDataStreamRowProcessingPublisher.java
- engine/core/src/main/java/org/datacleaner/job/runner/SourceTableRowProcessingPublisher.java
- engine/core/src/test/java/org/datacleaner/test/full/scenarios/TransformationAndFilteringInOutputDataStreamsTest.java
> Consumer sorting in output data stream

- desktop/ui/src/main/java/org/datacleaner/windows/CompositeDatastoreDialog.java
> Composite datastore scrollbar

- desktop/ui/src/main/java/org/datacleaner/user/DemoConfiguration.java
- desktop/ui/src/main/resources/datacleaner-home/jobs/OrderDB Customers and Employees union.analysis.xml
Fixes #755
The most boring job ever, but from this data I have no better idea. Thought about "sending out an postcard / email with Christmas wishes to all the people connected to the organization, so customers and employees", but these two tables do not have uniform data... Anyone?
> Example union job.

- monitor/services/src/main/java/org/datacleaner/monitor/server/MetricValueUtils.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ExecutionCancellationController.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/JobDeletionController.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ResultFileController.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ResultMetricsController.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/MetricValueUtilsTest.java
We came across this issue that metrics are not extracted from analyzer results that are wrapped in a future object.
> Made metric extraction work on results wrapped in AnalyzerResultFuture

- testware/src/main/java/org/datacleaner/test/AssertHelper.java
- testware/src/test/java/org/datacleaner/test/AssertHelperTest.java
> Utility for masking file paths when comparing against the benchmark

- components/basic-analyzers/src/test/java/org/datacleaner/beans/NumberAnalyzerTest.java
- engine/core/src/main/java/org/datacleaner/result/renderer/CrosstabTextRenderer.java
- engine/core/src/test/java/org/datacleaner/components/filter/MaxRowsFilterTest.java
- pom.xml
> Feature/upgrade to metamodel 4.4.0

- desktop/ui/src/main/java/org/datacleaner/windows/DataHubDatastoreDialog.java
- engine/core/src/main/java/org/datacleaner/metamodel/datahub/DataHubUpdateBuilder.java
- engine/core/src/test/java/org/datacleaner/metamodel/datahub/DataHubUpdateBuilderTest.java
- engine/core/src/test/java/org/datacleaner/metamodel/datahub/utils/JsonUpdateDataBuilderTest.java
Just a few fixes for bugs we've run into.
> Datahub connector fixes

- desktop/ui/src/main/java/org/datacleaner/widgets/AbstractResourceTextField.java
> Added tooltip to the filename textfield

- components/writers/src/main/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzer.java
- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraph.java
- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
- engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
Fixes #781 
check if the sub-jobs are configured as well.
> Incompletely configured components in output data streams does not show in window

- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
> Issue #796: Fixed

- desktop/ui/src/main/java/org/datacleaner/actions/PublishFileToMonitorActionListener.java
- desktop/ui/src/main/java/org/datacleaner/actions/PublishResultToMonitorActionListener.java
> Issue #818: Added extension to uploaded filename

- monitor/services/src/main/resources/orderdb.script
- monitor/services/src/test/resources/expected_conf_file_generic.xml
- monitor/services/src/test/resources/expected_conf_file_lookup_insert_update.xml
- monitor/services/src/test/resources/expected_conf_file_specific_datastore.xml
- monitor/services/src/test/resources/expected_conf_file_specific_lookup_another_ds.xml
- monitor/services/src/test/resources/expected_conf_file_specific_source_only.xml
> Issue #817: Copied CUSTOMERS table from desktop to monitor

- components/basic-filters/src/main/java/org/datacleaner/beans/filter/CaptureChangedRecordsFilter.java
- components/basic-filters/src/test/java/org/datacleaner/beans/filter/CaptureChangedRecordsFilterTest.java
Fixes #806 
I would love a review by @ankit2711 - can you check it?
> Issue #806: Nano-second precision in CaptureChangedRecords filter

- components/basic-filters/src/main/java/org/datacleaner/beans/filter/EqualsFilter.java
- components/basic-filters/src/test/java/org/datacleaner/beans/filter/EqualsFilterTest.java
> Issue #847: Fixed

- engine/core/src/main/java/org/datacleaner/metamodel/datahub/DataHubDataSet.java
This is a small change that saves 1 REST call at the end of the execution of the job. Until now, the job ended when the REST call returned an empty result. Now, each returned batch of records is counted. The job stops when the number of returned records is less than the requested number of records.
> Stop when returned rows is less than requested rows

- api/src/main/java/org/datacleaner/api/UsageMeteringMessage.java
> component message to be used for metering

- desktop/ui/src/main/java/org/datacleaner/windows/JsonDatastoreDialog.java
>  Made Json Datastore use Resource Selector.

- engine/core/src/main/java/org/datacleaner/components/convert/ConvertToBooleanTransformer.java
- engine/core/src/test/java/org/datacleaner/components/convert/ConvertToBooleanTransformerTest.java
Added "Y" and "N" values to the boolean tokens. This is useful in many obvious scenarios.
> Added Y/N values in "Convert to Boolean" default tokens

- engine/core/src/main/java/org/datacleaner/connection/MongoDbDatastore.java
- pom.xml
Do not merge yet - we would want the MM 4.4.1 release to be final first. But this PR confirms that it is building well and all that.
> Upgraded to MetaModel 4.4.1 using the staged repository

- engine/core/src/main/java/org/datacleaner/job/runner/CompositeAnalysisListener.java
- engine/core/src/main/java/org/datacleaner/job/runner/RowProcessingMetricsImpl.java
- engine/core/src/test/java/org/datacleaner/test/full/scenarios/QueryOptimizationAndAnalysisListeningTest.java
This PR addresses #878 by making the logging and assertions easier to decipher. But I guess the issue itself isn't "solveable" since it was a local build issue that would never happen except for stupid guys like me who have corrupted local MetaModel JARs :)
> Improves ability to diagnose issues like #878

- desktop/ui/src/main/java/org/datacleaner/windows/OptionsDialog.java
OptionsDialog, remote components tab. Description text is spread to the full width of the panel. In the code, methods for creating the tab were moved into a separate private class in the same file.
> Bug #867 Nicer remote components tab

- engine/core/src/test/java/org/datacleaner/configuration/DataCleanerConfigurationUpdaterTest.java
DataCleanerConfigurationUpdaterTest: problem with resource path.
> Bug #869 configuration test fails on windows

- api/src/main/java/org/datacleaner/api/HasDistributionAdvice.java
- components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
- engine/core/src/main/java/org/datacleaner/descriptors/AnnotationBasedAnalyzerComponentDescriptor.java
- engine/core/src/main/java/org/datacleaner/descriptors/AnnotationBasedFilterComponentDescriptor.java
- engine/core/src/main/java/org/datacleaner/descriptors/AnnotationBasedTransformerComponentDescriptor.java
- engine/core/src/main/java/org/datacleaner/descriptors/SimpleComponentDescriptor.java
- engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
- engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
- engine/core/src/main/java/org/datacleaner/job/builder/ComponentBuilder.java
- engine/env/cluster/src/main/java/org/datacleaner/cluster/DistributedAnalysisRunner.java
- engine/env/cluster/src/test/java/org/datacleaner/cluster/ClusterTestHelper.java
- engine/env/cluster/src/test/java/org/datacleaner/cluster/DistributedAnalysisRunnerTest.java
- engine/env/spark/src/main/java/org/datacleaner/spark/SparkAnalysisRunner.java
> Issue #873: Added HasDistributionAdvice interface + check in job builder

- components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
- components/writers/src/main/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzer.java
- components/writers/src/test/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzerTest.java
Fixes #864 by enforcing max 31 chars [1]
[1] see http://stackoverflow.com/questions/3681868/is-there-a-limit-on-an-excel-worksheets-name-length for details on that restriction
> Issue #864: Fixed excel sheet name length

- engine/env/spark/src/main/java/org/datacleaner/spark/SparkAnalysisRunner.java
- engine/env/spark/src/main/java/org/datacleaner/spark/functions/AnalyzerResultReduceFunction.java
- engine/env/spark/src/main/java/org/datacleaner/spark/functions/RowProcessingFunction.java
- engine/env/spark/src/main/java/org/datacleaner/spark/functions/TuplesToTuplesFunction.java
Small and harmless improvements to Spark ;-)
Just making double sure that Travis doesn't disagree on the 'harmless' point :-P
> Improved Spark logging and made 'preserveParitioning' a variable

- desktop/ui/src/main/java/org/datacleaner/actions/SaveAnalysisResultActionListener.java
- engine/core/src/main/java/org/datacleaner/result/save/AnalysisResultSaveHandler.java
I originally wanted to solve #892 via PR #894. But since that one is causing some confusion and strange issues, this PR will at least alleviate the issue and give the user an option to partially save his result.
> Issue #892: Implemented a more coarse grained solution for DC 4.5.1

- components/html-rendering/src/main/scala/org/datacleaner/result/html/FlotChartLocator.scala
- components/html-rendering/src/test/scala/org/datacleaner/result/html/FlotChartLocatorTest.scala
- components/value-distribution/src/main/scala/org/datacleaner/beans/valuedist/ValueDistributionChartScriptHeadElement.scala
- components/value-distribution/src/test/scala/org/datacleaner/beans/valuedist/ValueDistributionResultHtmlRendererTest.scala
- components/visualization/src/main/scala/org/datacleaner/visualization/DensityAnalyzerChartScriptHeadElement.scala
- components/visualization/src/main/scala/org/datacleaner/visualization/ScatterAnalyzerChartScriptHeadElement.scala
- components/visualization/src/main/scala/org/datacleaner/visualization/StackedAreaAnalyzerChartScriptHeadElement.scala
Also updates Flotto 0.8.3
There seem to be an minor issue with the sizing of the graphs, they all need to scroll a few millimeters. However, I don't think it's related to this (it's the same issue with Flot 0.7), so I left it alone for now.
Fixes #840
> Wraps drawing calls in ready handler.

- desktop/api/src/main/java/org/datacleaner/util/ChartUtils.java
- desktop/ui/src/main/java/org/datacleaner/widgets/result/PatternFinderResultSwingRendererCrosstabDelegate.java
- desktop/ui/src/main/java/org/datacleaner/widgets/result/ValueDistributionResultSwingRendererGroupDelegate.java
- engine/core/src/main/java/org/datacleaner/util/SystemProperties.java
Fixes #904 
Instead of a chart + table, the results now only contain a table.
One minor (unintended) drawback of these result displays is that they don't include the summary statistics which the chart _also_ showed - The number of distinct values/patterns.
> Issue #904: Added chart thresholds for Pattern Finder and Value Dist

- desktop/ui/src/main/java/org/datacleaner/windows/HdfsUrlChooser.java
This is an attempt to make it possible to select directories, by making a context menu. I'm not sure it's the best way, as it has some discoverability issues, but it's a simple way.
Unfortunately, I cannot test it, as I have some issues creating my vagrant VMs (for getting access to an HDFS), so there's currently a good chance this doesn't work at all.
Fixes #915
> Adds right-click menu to directories so they can be selected

- components/basic-transformers/src/main/java/org/datacleaner/beans/transform/RegexParserTransformer.java
- components/basic-transformers/src/test/java/org/datacleaner/beans/transform/RegexParserTransformerTest.java
> Issue #918: Added regex matching modes FIND_FIRST and FIND_ALL

- desktop/ui/src/main/java/org/datacleaner/widgets/tree/SchemaTree.java
- desktop/ui/src/main/java/org/datacleaner/windows/DatastoreSynonymCatalogDialog.java
- monitor/ui/pom.xml
- pom.xml
Fixes #930 
Also fixed a minor POM inconsistency around the el-api version (not related at all to #930, but too small to report independently :-P).
First I fixed the injection issues that are there in SchemaTree.
But then I realized that the schema tree shouldn't be injected at all.
But at the end of the day - both corrections are good, so please review ;-)
> Issue #930: Fixed

- desktop/api/src/main/java/org/datacleaner/panels/TransformerComponentBuilderPanel.java
> Issue #927: Fixed

- desktop/ui/src/main/java/org/datacleaner/widgets/tree/SchemaTree.java
- desktop/ui/src/main/java/org/datacleaner/windows/DatastoreDictionaryDialog.java
Fixes #929. 
- made the library to included in the schema tree optional.
> made the library to included in the schema tree optional.

- desktop/api/src/main/java/org/datacleaner/widgets/visualization/ComponentScopeMenuBuilder.java
Just some minor improvements to javadoc etc.
@LosD please make sure that I didn't misunderstand this completely. I think these things was mostly incomplete or copy-paste issues.
> Making a bit more sense out of javadoc of ComponentScopeMenuBuilder

- components/basic-transformers/src/main/java/org/datacleaner/beans/transform/RegexParserTransformer.java
- components/basic-transformers/src/main/java/org/datacleaner/beans/transform/RegexSearchReplaceTransformer.java
- desktop/api/src/main/java/org/datacleaner/widgets/properties/PropertyWidgetPanel.java
- engine/core/src/main/java/org/datacleaner/util/StringUtils.java
- engine/core/src/test/java/org/datacleaner/util/StringUtilsTest.java
Added "Regular Expression Lesson" link from Java documentation.
Also fixed a minor thing about adding whitespace instead of linebreak
for property widget tooltips. And another minor thing about a needless
loop in StringUtils
Fixes #941
> Issue #941: Fixed

- engine/core/src/main/java/org/datacleaner/descriptors/DCClassVisitor.java
> Issue #957: Fixed by catching UnsupportedClassVersionError

- desktop/ui/src/main/java/org/datacleaner/cli/CliRunner.java
- desktop/ui/src/main/java/org/datacleaner/user/DesktopConfigurationReaderInterceptor.java
- desktop/ui/src/main/resources/datacleaner-home/conf.xml
- engine/core/src/main/java/org/datacleaner/configuration/DefaultConfigurationReaderInterceptor.java
- engine/core/src/main/java/org/datacleaner/descriptors/ClasspathScanDescriptorProvider.java
- engine/env/spark/src/main/java/org/datacleaner/spark/SparkConfigurationReaderInterceptor.java
- engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java
- engine/env/spark/src/test/resources/conf_hdfs.xml
- engine/env/spark/src/test/resources/conf_local.xml
- engine/xml-config/src/test/resources/example-configuration-all-datastore-types.xml
- engine/xml-config/src/test/resources/example-configuration-csv-with-special-chars.xml
- engine/xml-config/src/test/resources/example-configuration-valid.xml
- monitor/services/src/main/java/org/datacleaner/monitor/configuration/MonitorConfigurationReaderInterceptor.java
- monitor/services/src/main/resources/org/datacleaner/monitor/configuration/default-conf.xml
- monitor/ui/src/main/webapp/repository/demo/conf.xml
Trying to make the descriptor provider, task runner and storage provider optional configuration elements with good defaults.
Fixes #971
> Issue #971: Sanitize configuration elements

- api/src/main/java/org/datacleaner/descriptors/DescriptorProvider.java
- api/src/main/java/org/datacleaner/descriptors/DescriptorProviderState.java
- engine/core/src/main/java/org/datacleaner/descriptors/AbstractDescriptorProvider.java
- engine/core/src/main/java/org/datacleaner/descriptors/CompositeDescriptorProvider.java
- engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteDescriptorProvider.java
- monitor/services/src/main/java/org/datacleaner/monitor/configuration/SharedDescriptorProvider.java
Descriptor provider's state (level, message) was introduced. Remote descriptor provider informs about server availability.
> Feature #974

- engine/env/spark/src/main/java/org/datacleaner/spark/Main.java
- engine/env/spark/src/main/java/org/datacleaner/spark/SparkAnalysisResultFuture.java
- engine/env/spark/src/main/java/org/datacleaner/spark/SparkAnalysisRunner.java
- engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java
- engine/env/spark/src/test/java/org/datacleaner/spark/SparkAnalysisRunnerTest.java
- engine/env/spark/src/test/resources/jobProperties/noResult.properties
> Issue #988: Made spark module capable of skipping result reduction

- engine/core/src/main/java/org/datacleaner/descriptors/ClasspathScanDescriptorProvider.java
PR for  NoClassDefException exception while scanning the packages. 
(The tests pass now)
> catch the NoClassDefException exception

- desktop/ui/src/main/java/org/datacleaner/panels/SchemaTreePanel.java
- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
> Issue #960: Fixed

- components/writers/src/main/java/org/datacleaner/extension/output/AbstractOutputWriterAnalyzer.java
> Issue #998: Prevented issue by introducing a field uniqueness validation

- components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceMultipleFieldsTransformer.java
- components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceUnit.java
- components/fuse/src/main/java/org/datacleaner/components/fuse/FuseStreamsComponent.java
- components/fuse/src/test/java/org/datacleaner/components/fuse/CoalesceUnitTest.java
- components/fuse/src/test/java/org/datacleaner/components/fuse/FuseStreamsComponentIntegrationTest.java
Fixes #923 and related columnname serialization issue in coalesceunit
> Issue #923: Coalesce transformer preview fix

- engine/core/src/main/java/org/datacleaner/connection/ElasticSearchDatastore.java
- pom.xml
Tests that the staged Apache MetaModel 4.5.0 release will work in DataCleaner.
Fixes #977 (among other things)
> Added MetaModel 4.5.0 (staged release) for testing

- desktop/ui/src/main/java/org/datacleaner/guice/DCModuleImpl.java
- engine/core/src/main/java/org/datacleaner/configuration/DefaultConfigurationReaderInterceptor.java
- engine/core/src/main/java/org/datacleaner/util/HadoopResource.java
- engine/core/src/main/java/org/datacleaner/util/convert/HdfsResourceTypeHandler.java
- engine/core/src/main/java/org/datacleaner/util/convert/ResourceConverter.java
- engine/core/src/test/java/org/datacleaner/util/convert/HdfsResourceTypeHandlerTest.java
- engine/core/src/test/java/org/datacleaner/util/convert/ResourceConverterTest.java
- engine/env/spark/src/main/java/org/datacleaner/spark/Main.java
- engine/env/spark/src/main/java/org/datacleaner/spark/SparkJobContext.java
- engine/env/spark/src/main/java/org/datacleaner/spark/utils/HdfsHelper.java
- engine/env/spark/src/main/java/org/datacleaner/spark/utils/ResultFilePathUtils.java
- engine/env/spark/src/test/java/org/datacleaner/spark/JobResultPathTest.java
- engine/env/spark/src/test/java/org/datacleaner/spark/SparkAnalysisRunnerTest.java
This PR goes some way to fix #1016, but it is just the first step.
Fetching Hadoop 'Configuration' from SparkContext and use it for all resources in spark runner.
> Use SparkContext.hadoopConfiguration()

- engine/core/src/main/java/org/datacleaner/reference/DatastoreDictionary.java
> Avoid DISTINCT clause in DatastoreDictionary on non-optimized datastores

- engine/core/src/main/java/org/datacleaner/reference/DatastoreDictionary.java
- engine/core/src/main/java/org/datacleaner/reference/DatastoreSynonymCatalog.java
- engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
- engine/xml-config/src/main/resources/configuration.xsd
- engine/xml-config/src/test/java/org/datacleaner/configuration/JaxbConfigurationReaderTest.java
- engine/xml-config/src/test/resources/example-configuration-all-reference-data-types.xml
> Issue #1018: Added flags to configuration.xsd - loadIntoMemory

- README.md
Just a small change, I'm making a demo of PRs for @arjansh :)
> Added description of 'env' module

- components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceMultipleFieldsTransformer.java
- components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceUnit.java
- components/fuse/src/main/java/org/datacleaner/components/fuse/FuseStreamsComponent.java
- components/fuse/src/test/java/org/datacleaner/components/fuse/CoalesceUnitConverterTest.java
- components/fuse/src/test/java/org/datacleaner/components/fuse/CoalesceUnitTest.java
- desktop/ui/src/main/java/org/datacleaner/panels/fuse/CoalesceUnitPanel.java
- desktop/ui/src/main/java/org/datacleaner/panels/fuse/ColumnListMultipleCoalesceUnitPropertyWidget.java
- desktop/ui/src/main/java/org/datacleaner/panels/fuse/StreamColumnMatrixMultipleCoalesceUnitPropertyWidget.java
This avoid problems with copied job and transformers affecting each other.
Fixes #1045
> Make CoalesceUnit immutable

- engine/core/src/main/java/org/datacleaner/components/composition/AbstractWrappedAnalysisJobTransformer.java
- engine/xml-config/src/main/java/org/datacleaner/beans/composition/InvokeChildAnalysisJobTransformer.java
- engine/xml-config/src/test/java/org/datacleaner/components/composition/InvokeChildAnalysisJobTransformerTest.java
- engine/xml-config/src/test/resources/childjob.analysis.xml
While I was building an example of using the ```Invoke child Analysis job``` transformation I discovered that it was actually having a pretty sincere bug. So this fixes it and also adds an integration test to improve the test coverage of this piece.
> Fixed list-index bug in Invoke child job transformer + integration test

- desktop/ui/src/main/java/org/datacleaner/widgets/tree/SchemaTree.java
My replacement PR for #983 with the fix as I suggested it.
> Fixes #982 by making sure that listener reactions happens in AWT thread

- components/fuse/src/main/java/org/datacleaner/components/fuse/CoalesceUnit.java
- desktop/api/src/main/java/org/datacleaner/widgets/properties/AbstractPropertyWidget.java
- desktop/api/src/main/java/org/datacleaner/widgets/properties/MinimalPropertyWidget.java
- desktop/ui/src/main/java/org/datacleaner/panels/fuse/CoalesceUnitPanel.java
- desktop/ui/src/main/java/org/datacleaner/panels/fuse/ColumnListMultipleCoalesceUnitPropertyWidget.java
- desktop/ui/src/main/java/org/datacleaner/panels/fuse/StreamColumnMatrixMultipleCoalesceUnitPropertyWidget.java
- engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
Fixes Fuse/Coalesce and Union component.
Fixes #1048
> CoalsesceUnit-based component configure fixes

- monitor/ui/src/main/java/org/datacleaner/monitor/resources/scheduling.css
- monitor/ui/src/main/webapp/styles.css
> Changed the css so that all alerts are visible to edit

- components/value-distribution/src/main/java/org/datacleaner/result/AbstractValueCountingAnalyzerResult.java
> removed 'unique' label from value distribution 'value count' metric

- engine/core/src/main/java/org/datacleaner/descriptors/AnnotationBasedAnalyzerComponentDescriptor.java
- engine/core/src/main/java/org/datacleaner/descriptors/AnnotationBasedFilterComponentDescriptor.java
- engine/core/src/main/java/org/datacleaner/descriptors/AnnotationBasedTransformerComponentDescriptor.java
- engine/core/src/main/java/org/datacleaner/descriptors/SimpleComponentDescriptor.java
- engine/core/src/main/java/org/datacleaner/result/CategorizationResult.java
- engine/core/src/main/java/org/datacleaner/result/CategorizationResultReducer.java
- engine/core/src/main/java/org/datacleaner/storage/RowAnnotationImpl.java
- engine/core/src/test/java/org/datacleaner/components/tablelookup/TableLookupTransformerTest.java
- engine/core/src/test/java/org/datacleaner/result/CategorizationResultReducerTest.java
- engine/env/spark/src/main/java/org/datacleaner/spark/functions/AnalyzerResultReduceFunction.java
> Issue #1095: Added reducer for CategorizationResult

- monitor/services/src/main/java/org/datacleaner/monitor/server/ui/MonitorUIPreferences.java
- monitor/services/src/main/java/org/datacleaner/monitor/shared/ClientConfig.java
- monitor/services/src/main/java/org/datacleaner/monitor/shared/DictionaryClientConfig.java
- monitor/ui/src/main/webapp/datastores.xhtml
- monitor/ui/src/main/webapp/login.xhtml
- monitor/ui/src/main/webapp/repository.xhtml
- monitor/ui/src/main/webapp/template.xhtml
- monitor/ui/src/main/webapp/template_popup.xhtml
- monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/CustomizeJobClickHandler.java
- monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/SchedulePanel.java
Fixes #1081 by introducing a spring bean with UI preference flags.
My idea is that in DC EE we will use the normal ```datacleaner-monitor.preferences``` to set these flags.
> Issue #1081: Implemented UI preferences for Webstart/JNLP and more.

- api/src/main/java/org/datacleaner/descriptors/DescriptorProvider.java
- pom.xml
It was a single error in DescriptorProvider.
Also upgraded the plugin.
> Fixes #1078 - javadoc errors

- components/pattern-finder/src/main/java/org/datacleaner/beans/stringpattern/PatternFinderAnalyzer.java
- desktop/ui/src/test/resources/documentation/pattern_finder.html
> Issue #1104: Fixed

- components/basic-transformers/src/main/java/org/datacleaner/beans/transform/RemoveSubstringTransformer.java
- components/basic-transformers/src/test/java/org/datacleaner/beans/transform/RemoveSubstringTransformerTest.java
Fixes #1108 
I blame @LosD ;-) Please review.
> Issue #1108: Fixed

- desktop/ui/src/main/java/org/datacleaner/windows/ResultWindow.java
- engine/core/src/main/java/org/datacleaner/util/batch/BatchTransformationBuffer.java
- engine/remote-components/src/main/java/org/datacleaner/components/remote/RemoteTransformer.java
- engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteDescriptorProviderImpl.java
- engine/rest-client/src/main/java/org/datacleaner/restclient/RESTClientImpl.java
> Better catching exception

- monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/command/AddAlertCommand.java
Fixes #1130
fixed 'add alert' button. The next button was inserted instead of the
save button
> Fixes #1130 'add alert'  button

- components/basic-transformers/src/main/java/org/datacleaner/beans/transform/RemoveSubstringTransformer.java
- components/basic-transformers/src/test/java/org/datacleaner/beans/transform/RemoveSubstringTransformerTest.java
Fixes #1151
The approach to removing substrings has been changed a bit so that the code flow is not too nested into a lot of if-else's.
I think the test case is now rather good.
> Case insensitive "Remove substring"

- desktop/ui/src/main/java/org/datacleaner/widgets/options/RemoteComponentsOptionsPanel.java
> fix of moving text in option dialog panel

- engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteTransformerDescriptorImpl.java
- engine/rest-client/src/main/java/org/datacleaner/restclient/ComponentRESTClient.java
- engine/rest-client/src/main/java/org/datacleaner/restclient/RESTClient.java
- engine/rest-client/src/main/java/org/datacleaner/restclient/RESTClientImpl.java
Was working on #1166 but didn't quite finish what I was doing ... Anyways, these are a few code tweaks that I found that I meant to push before I go on vacation ;-)
> Minor introductions of final etc.

- components/visualization/pom.xml
> Enable unavailable html renderers

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLayoutTransformer.java
- engine/core/src/main/java/org/datacleaner/reference/DatastoreDictionary.java
- engine/core/src/main/java/org/datacleaner/reference/RegexStringPattern.java
- engine/core/src/main/java/org/datacleaner/reference/SimpleSynonymCatalog.java
- engine/core/src/main/java/org/datacleaner/reference/TextFileDictionary.java
> Fixed #1207

- desktop/ui/src/main/java/org/datacleaner/util/RemoteServersUtils.java
- engine/core/src/main/java/org/datacleaner/descriptors/CompositeDescriptorProvider.java
- engine/core/src/test/java/org/datacleaner/descriptors/CompositeDescriptorProviderTest.java
- engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
- monitor/services/src/main/java/org/datacleaner/monitor/configuration/ConfigurationFactory.java
#1211  
Fix of problem - ClassCastException thrown when logging in to DataCloud
> Fix of problem  - ClassCastException thrown when logging in to DataCloud

- engine/core/src/main/java/org/datacleaner/descriptors/EnumerationValue.java
- engine/remote-components/src/main/java/org/datacleaner/descriptors/JsonSchemaConfiguredPropertyDescriptorImpl.java
- engine/rest-client/src/main/java/org/datacleaner/restclient/Serializator.java
Is important in UI, when suggesting mapping for @MappedProperty property.
> Support for enumeration aliases in remote transformer

- engine/core/src/main/java/org/datacleaner/descriptors/SimpleComponentDescriptor.java
- engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteDescriptorProviderImpl.java
- engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteTransformerDescriptorImpl.java
- engine/rest-client/src/main/java/org/datacleaner/restclient/ComponentList.java
- engine/rest-client/src/test/java/org/datacleaner/restclient/SerializatorTest.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ComponentControllerV1.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/components/ComponentInfoTest.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/components/ComponentListTest.java
#1243
Tooltip problem - remote transformers
> Refactor for all annotation in transformer class

- engine/env/spark/src/main/java/org/datacleaner/spark/utils/HadoopConfigurationUtils.java
- engine/env/spark/src/test/java/org/datacleaner/spark/HadoopConfigurationUtilsTest.java
Utility class for checking the validity of a job ran on Hadoop
> Utility class for checking the validity of a job ran on Hadoop

- components/basic-analyzers/src/main/java/org/datacleaner/beans/CompletenessAnalyzer.java
- components/basic-analyzers/src/test/java/org/datacleaner/beans/CompletenessAnalyzerTest.java
- desktop/ui/src/test/resources/documentation/completeness_analyzer.html
> Issue #1263: Added NULL and BLANK_OR_NULL conditions to Completeness

- engine/core/src/main/java/org/datacleaner/util/batch/BatchTransformationBuffer.java
> Fix for stackoverflow in remote transformer

- desktop/ui/src/main/java/org/datacleaner/windows/ResultWindow.java
> change the sentence for processing finished message

- engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteDescriptorProviderImpl.java
- engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteTransformerDescriptorImpl.java
- engine/rest-client/src/main/java/org/datacleaner/restclient/RESTClientException.java
- engine/rest-client/src/test/java/org/datacleaner/restclient/SerializatorTest.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/components/InputColumnAndMappedPropertyRewriter.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/components/InputRewriter.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/components/InputRewriterController.java
These issues showed up when I checked out DC into my new eclipse. Felt that they would be easy and good to fix :)
> Fixed a few minor code style issues that gave compiler warnings.

- desktop/ui/src/main/java/org/datacleaner/guice/DCModuleImpl.java
- desktop/ui/src/main/java/org/datacleaner/util/MutableRemoteServerConfigurationImpl.java
- engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java
- engine/remote-components/src/main/java/org/datacleaner/configuration/RemoteServerConfigurationImpl.java
- engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
#1303 
There was problem of initialization of RemoteServerConfiguration.
Now all enviroments have same object with the same data.
> #1303 Bug fix. Changes in creating of RemoteServerConfiguration

- desktop/ui/src/main/java/org/datacleaner/util/MutableRemoteServerConfigurationImpl.java
- engine/remote-components/src/main/java/org/datacleaner/configuration/RemoteServerConfigurationImpl.java
#1309 DataCloud icon unrespons on change of credentials in DataCloud options dialog.
I fixed this bug
> #1309 - Check status of DataCloud also after credentials update.

- engine/core/src/main/java/org/datacleaner/connection/ElasticSearchDatastore.java
> Use credentials for REST mode.

- components/basic-filters/src/main/java/org/datacleaner/beans/filter/DateRangeFilter.java
- engine/core/src/main/java/org/datacleaner/extensions/ClassLoaderUtils.java
Fixes #1325 
DateRangeFilter's description was probably copied from NumberRangeFilter's description and it mentioned "number value" instead of "date value".
> DateRangeFilter's description fix

- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/ComponentControllerV1.java
> Fix for remote components authorization hook

- engine/xml-config/src/main/java/org/datacleaner/configuration/DomConfigurationWriter.java
- engine/xml-config/src/test/java/org/datacleaner/configuration/DomConfigurationWriterTest.java
> externalizes Json datastore

- desktop/ui/src/main/java/org/datacleaner/panels/NewsChannelPanel.java
- desktop/ui/src/main/java/org/datacleaner/widgets/NewsChannelStatusLabel.java
> News Channel improvements

- engine/rest-client/src/main/java/org/datacleaner/restclient/Serializator.java
- monitor/services/src/main/java/org/datacleaner/monitor/configuration/ComponentStoreImpl.java
> #1389 - datacloud json - ignore unknown properties

- desktop/ui/src/main/java/org/datacleaner/panels/NewsChannelPanel.java
> fixed url to website news

- monitor/documentation/src/main/java/org/datacleaner/documentation/swagger/SwaggerJSONController.java
swagger json generation was not working for controllers that had annotations in ancestor class
> Fix in swagger json

- desktop/ui/src/main/java/org/datacleaner/windows/DatastoreDictionaryDialog.java
- desktop/ui/src/main/java/org/datacleaner/windows/RegexStringPatternDialog.java
- desktop/ui/src/main/java/org/datacleaner/windows/SimpleStringPatternDialog.java
> Increased the size of the reference data dialogs

- api/src/main/java/org/datacleaner/api/ComponentScope.java
- engine/remote-components/src/main/java/org/datacleaner/descriptors/RemoteTransformerDescriptorImpl.java
> #1409 Componet enabled problem with boolen - Boolean..

- desktop/api/src/main/java/org/datacleaner/panels/AbstractComponentBuilderPanel.java
> #1413 - direct link to datacloud access rights from disabled transformer

- monitor/ui/src/main/java/org/datacleaner/monitor/dashboard/widgets/WelcomePanel.ui.xml
- monitor/ui/src/main/webapp/styles.css
Fixes #1416 
A few small corrections at the monitor's home page.
> #1416: monitor ui glitches at home page.

- components/basic-transformers/src/main/java/org/datacleaner/beans/numbers/GenerateIdTransformer.java
The offset field could be confusing, this describes it a little.
Fixes #1361
> Add a description for GenerateId offset

- desktop/api/src/main/java/org/datacleaner/actions/PreviewTransformedDataActionListener.java
- desktop/api/src/main/java/org/datacleaner/widgets/ExecuteButtonOptions.java
- desktop/ui/src/test/java/org/datacleaner/actions/PreviewTransformedDataActionListenerTest.java
- desktop/ui/src/test/resources/benchmark/PreviewTransformedDataActionListenerTest-testFilterWithCoalesce.analysis.xml
- desktop/ui/src/test/resources/benchmark/PreviewTransformedDataActionListenerTest-testPreviewTransformationInMultiStreamGeneratedOutputDataStream.analysis.xml
- engine/core/src/main/java/org/datacleaner/job/builder/AnalysisJobBuilder.java
- engine/core/src/main/java/org/datacleaner/util/PreviewUtils.java
Unfiltered Analyzers might mean that too much data will be loaded.
Unfiltered transformers with results will _not_ be filtered.
Fixes #1371
I'm thinking I'd like to add a few test cases before merging.
> Fix most of run n records cases (but there can still be slip-ups)

- components/basic-filters/src/main/java/org/datacleaner/beans/filter/EqualsFilter.java
Do not update the _operand field in the filter method.
Fixes #1448
> Fix a race condition in equals filter

- desktop/ui/src/main/java/org/datacleaner/actions/SaveAnalysisJobActionListener.java
- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
> Check if the job has been saved been closing the window

- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
> Windows menu item are smaller

- pom.xml
> Bump MM to 4.5.4

- components/basic-filters/src/main/java/org/datacleaner/beans/filter/CompareFilter.java
- components/basic-filters/src/test/java/org/datacleaner/beans/filter/CompareFilterTest.java
Solves #1435. 
IN operator was added in CompareFilter.
> #1435: IN operator support in CompareFilter.

- components/javascript/src/test/java/org/datacleaner/beans/script/JavaScriptTransformerTest.java
> Javascript transformer parseInt issue.

- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/JobsFolderController.java
- monitor/ui/src/main/webapp/scheduling.xhtml
Solves #1433. 
In monitor, job file upload now supports multiple selection.
> #1433: Multiple job files upload in monitor.

- api/src/main/java/org/datacleaner/api/HideOutputColumns.java
- engine/core/src/main/java/org/datacleaner/job/builder/TransformerComponentBuilder.java
Fixes #1451 
Hide the output columns of a transformer
> Hide the output columns of a transformer

- desktop/ui/src/main/java/org/datacleaner/widgets/DataCloudStatusLabel.java
> #1465 - Bug - Status display of DataCloud is wrong for new DataCleaner

- desktop/ui/src/main/java/org/datacleaner/windows/AnalysisJobBuilderWindowImpl.java
> Disable "Save" and "Save as" when datastore is null

- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/RepositoryZipController.java
fixes #1077. 
Improved the upload zip folder controller
> fixes #1077. Improved the upload zip folder controller

- engine/core/src/main/java/org/datacleaner/metamodel/datahub/DataHubDataContext.java
- engine/core/src/main/java/org/datacleaner/metamodel/datahub/DataHubUpdateConnection.java
Has been tested with the latest Datahub master. Works as expected.
> Removed deprecated datahub urls 

- components/writers/src/main/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzer.java
Performance fix in case user has checked "overwrite sheet if exists" in CreateExcelSpreadsheetAnalyzer.
Fixes #1529
> Do not check Excel for existing sheet if overwrite is okay

- engine/core/src/main/java/org/datacleaner/connection/JdbcDatastore.java
fixed the exception for jtds driver in case of single connections
fixes #1201.
> fixed the exception for jtds driver in case of single connections

- monitor/ui/src/main/webapp/repository/demo/jobs/Copy employees to customer table.analysis.xml
Fixes #1060 
The file will be create relative to the repository tenant folder. The file contains only 23 rows and the job is set to overwrite the file.
> Changed the sample job to insert into a csv file

- desktop/ui/src/main/java/org/datacleaner/windows/CsvDatastoreDialog.java
- desktop/ui/src/main/java/org/datacleaner/windows/ExcelDatastoreDialog.java
- desktop/ui/src/main/java/org/datacleaner/windows/FixedWidthDatastoreDialog.java
>  Hide column names panel everywhere

- Formatter-IDEA.xml
This fixes a discrepancy between IDEA and Eclipse
> Move static imports to the top

- api/src/main/java/org/datacleaner/metadata/ColumnMeaning.java
Resolves #1601 
"Job title" vs "person title"
"landline" vs "moble"
> #1601 ColumnMeaning update

- desktop/ui/src/main/java/org/datacleaner/windows/SourceTableConfigurationDialog.java
fixes #1623.
added max height for source table configuration dialog
>  added max height for source table configuration dialog

- engine/core/src/main/java/org/datacleaner/job/builder/AbstractComponentBuilder.java
fixes #1616.
update the source column in outputstream job builder
> update the source column in outputstream job builder

- pom.xml
> upgrade dependency vfs to 2.1

- monitor/services/src/main/java/org/datacleaner/monitor/server/SchedulingServiceImpl.java
Fixes #1638 
Scheduling configuration is again available in Monitor's GUI (reversion of #1532). The speed of jobs loading at /scheduling page is decreased again.
> #1638 Scheduling configuration again available in GUI

- Formatter-IDEA.xml
This tweaks some settings and re-enables JavaDoc formatting.
@jhorcicka Can I get you to check this when you have the time?
> A few updates to IDEA codestyle file

- monitor/ui/src/main/java/org/datacleaner/monitor/resources/scheduling.css
- monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/SchedulePanel.java
- monitor/widgets/src/main/java/org/datacleaner/monitor/scheduling/widgets/SchedulePanel.ui.xml
Fixes #1656 
This PR adds the latest execution details to the schedule overview panel. However, the GWT throws a Javascript error, which I have no idea what it is causing it.
> Adding the latest execution status to the page

- monitor/services/src/main/java/org/datacleaner/monitor/configuration/PlaceholderAnalysisJob.java
- monitor/services/src/main/java/org/datacleaner/monitor/configuration/PlaceholderAnalysisJobWithAnalyzers.java
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/JobInvocationController.java
- monitor/services/src/test/java/org/datacleaner/monitor/server/controllers/JobInvocationControllerTest.java
- monitor/services/src/test/resources/example_repo/tenant7/conf.xml
- monitor/services/src/test/resources/example_repo/tenant7/jobs/email_standardizer_to_db.analysis.xml
> Functionality for invoking analyzer jobs on DC monitor

- desktop/ui/src/main/java/org/datacleaner/util/GraphUtils.java
Resolves #1664 
Edges among components were made lighter. Complex jobs are now more readable.
> #1664 Ligther connection links

- api/src/main/java/org/datacleaner/metadata/ColumnMeaning.java
Resolves #1666 
Name initials item was added to ColumnMeaning.
> #1666 Initials in ColumnMeaning

- monitor/extensions/csv-datastore-wizard/src/main/resources/org/datacleaner/monitor/server/wizard/CsvDatastoreUploadOrExistingFileWizardPage.html
- monitor/services/src/main/java/org/datacleaner/monitor/server/controllers/JobsFolderController.java
- monitor/ui/src/main/webapp/scheduling.xhtml
Fixes #1673 
* 50mb->50 MB. 
* Space after each comma in the list of file names after successful upload.
> #1673 small UI fixes

- engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
fixes #1686. fixes open jobs as template with outputstreams
> fixes open jobs as template with outputstreams

- desktop/ui/src/main/java/org/datacleaner/windows/ResultWindow.java
> fixes value distribution scrollbar

- desktop/ui/src/test/java/org/datacleaner/cli/SampleJobsIT.java
- engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
- engine/xml-config/src/main/java/org/datacleaner/job/JaxbJobReader.java
> Optimization for job and config reader (5.1 branch)

- desktop/ui/pom.xml
- oss-branding/src/main/java/org/datacleaner/branding/ColorsResourceBundle.java
- oss-branding/src/main/java/org/datacleaner/branding/DesktopColorsResourceBundle.java
- oss-branding/src/main/resources/desktop-colors.properties
- oss-branding/src/test/java/org/datacleaner/branding/DesktopColorsResourceBundleTest.java
- oss-branding/src/test/java/org/datacleaner/branding/ImageLoadingResourceBundleTest.java
Related to already closed issue #1719. 
Colors were put into a properties file (in the same manner as image paths).
> #1719 Colors were put into a properties file

- desktop/ui/src/main/java/org/datacleaner/widgets/properties/MultipleMappedComboBoxPropertyWidget.java
Resolves #1729 
A new public getter MultipleMappedComboBoxPropertyWidget::getMappedComboBoxes.
> MultipleMappedComboBoxPropertyWidget: getMappedComboBoxes.

- components/uniqueness/src/main/java/org/datacleaner/beans/uniqueness/UniqueKeyCheckAnalyzer.java
- components/writers/src/main/java/org/datacleaner/extension/output/CreateCsvFileAnalyzer.java
- components/writers/src/main/java/org/datacleaner/extension/output/CreateExcelSpreadsheetAnalyzer.java
fixes #1731
delete the temporary files when the writers are finished.
> delete the temporary files when the writers are finished.

- README.md
The module list in README is not showing correctly in github. I updated indents and removed modules I could not find.
> Update README modules list

- .gitignore
- .travis.yml
- api/pom.xml
- desktop/ui/pom.xml
- engine/xml-config/pom.xml
- pom.xml
> Issue #1782: Upgraded/added dependencies needed for Java 9/10 support.

- desktop/ui/src/main/java/org/datacleaner/connection/DatastoreDescriptors.java
- desktop/ui/src/main/java/org/datacleaner/widgets/tree/SchemaTree.java
- desktop/ui/src/main/java/org/datacleaner/widgets/tree/SortedDefaultMutableTreeModel.java
Fixes #1722 
Tested it on both "split" (displays "Tokenizer") and "join" (displays "Table lookup")
> 1722 better component search

- desktop/ui/src/main/java/org/datacleaner/widgets/visualization/JobGraphLayoutTransformer.java
- desktop/ui/src/main/java/org/datacleaner/windows/FixedWidthDatastoreDialog.java
- engine/core/pom.xml
- engine/core/src/main/java/org/datacleaner/job/runner/CompositeAnalysisListener.java
- engine/xml-config/src/test/java/org/datacleaner/configuration/JaxbConfigurationReaderTest.java
- pom.xml
I had some strange issues building this locally, but trying with a PR to see what happens on Travis ...
A note about the `CompositeAnalysisListener` changes: I made these because of some of the failed tests that I saw locally initially. Some of the spark jobs failed in hundreds of different ways and my build logs got swamped in repeated exception traces. So I added the AtomicBoolean to keep track of whether or not to log the complete stack trace (only doing that on the initial error now).
> MetaModel 5.2.0

- components/pattern-finder/src/main/java/org/datacleaner/beans/stringpattern/PatternFinderAnalyzer.java
- components/pattern-finder/src/main/java/org/datacleaner/beans/stringpattern/TokenizerConfiguration.java
> Issue #1596: Removed dependence on locale-specific DecimalFormatSymbols.

- engine/core/src/main/java/org/datacleaner/util/ChangeAwareObjectInputStream.java
I noticed this when I built the project on AdoptOpenJDK. One of our
tests revealed that some of our result classes (written in Scala) have
different serialVersionUIDs, probably differing based on the JVM
implementation details.
```
[ERROR] testScatterPlotVisualizationComponentLoading(org.datacleaner.test.scenario.OpenAnalysisResultTest)
Time elapsed: 0.02 s  <<< ERROR!
java.lang.IllegalStateException: java.io.InvalidClassException:
org.datacleaner.visualization.ScatterGroup$$anonfun$1; local class
incompatible: stream classdesc serialVersionUID = -4484196027050979344,
local class serialVersionUID = 0
at org.datacleaner.test.scenario.OpenAnalysisResultTest.testScatterPlotVisualizationComponentLoading(OpenAnalysisResultTest.java:94)
Caused by: java.io.InvalidClassException: …
```
> Fixed deserialization when serialVersionUID mismatches.

- datastores/basic-datastores/pom.xml
- datastores/basic-datastores/src/main/java/org/datacleaner/connection/ArffDatastore.java
- datastores/basic-datastores/src/test/resources/example.arff
- engine/xml-config/src/main/java/org/datacleaner/configuration/DomConfigurationWriter.java
- engine/xml-config/src/main/java/org/datacleaner/configuration/JaxbConfigurationReader.java
- engine/xml-config/src/main/resources/configuration.xsd
- engine/xml-config/src/test/java/org/datacleaner/configuration/JaxbConfigurationReaderTest.java
- engine/xml-config/src/test/resources/example-configuration-all-datastore-types.xml
- pom.xml
I guess this is probably the first of two PRs ... First creating the code to support .arff datastores (support for which was recently added in Apache MetaModel). The obvious successor MR would add UI support.
> Added support for ARFF datastores (no UI elements though).

- datastores/basic-datastores/src/main/java/org/datacleaner/connection/JdbcDatastore.java
See #1824 for discussion/reasoning behind this change.
> Improved exception messages thrown by JdbcDatastore.

- pom.xml
> Fixed #1849 by upgrading postgresql driver.

- engine/core/src/main/java/org/datacleaner/reference/TextFileSynonymCatalog.java
- engine/core/src/main/java/org/datacleaner/result/save/AnalysisResultSaveHandler.java
- engine/core/src/main/java/org/datacleaner/util/convert/MapStringToStringConverter.java
- engine/env/spark/src/main/java/org/datacleaner/spark/functions/CsvParserFunction.java
- pom.xml
Upgrading to MetaModel 5.3.5. And updated a few dependencies that where also updated in MetaModel.
> Dependency upgrades

- desktop/ui/src/main/java/org/datacleaner/actions/OpenAnalysisJobActionListener.java
- desktop/ui/src/main/java/org/datacleaner/guice/DCModuleImpl.java
- pom.xml
This should help on #1897 ... At least with this change I am able to run DC on a new JRE.
> Defines/upgrade the verison of Guide, adding JRE 9+ compatibility
